//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.APIResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.APIResources.MessagesAPI", typeof(MessagesAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creación de cuenta.
        /// </summary>
        public static string AccountCreation {
            get {
                return ResourceManager.GetString("AccountCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim Concepto.
        /// </summary>
        public static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola,  &apos;{0}&apos; - &apos;{1}&apos;..
        /// </summary>
        public static string EmailCAChangeStatusMsg {
            get {
                return ResourceManager.GetString("EmailCAChangeStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo de aprobación - Notificación de cambio de estado.
        /// </summary>
        public static string EmailCAChangeStatusNotif {
            get {
                return ResourceManager.GetString("EmailCAChangeStatusNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tiene alguna pregunta/problema visite nuestra página o contáctenos..
        /// </summary>
        public static string EmailInfoSupport {
            get {
                return ResourceManager.GetString("EmailInfoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido &apos;{0}&apos; - &apos;{1}&apos;, para restablecer su clave ingrese al siguiente link..
        /// </summary>
        public static string EmailResetPasswordMsg {
            get {
                return ResourceManager.GetString("EmailResetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido &apos;{0}&apos;  - &apos;{1}&apos;, deberás confirmar tu cuenta..
        /// </summary>
        public static string EmailWelcomeMsg {
            get {
                return ResourceManager.GetString("EmailWelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta {0} se encuentra bloqueada..
        /// </summary>
        public static string ErrorAccountBlocked {
            get {
                return ResourceManager.GetString("ErrorAccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta {0} no posee licencia activa..
        /// </summary>
        public static string ErrorAccountNotActivelicense {
            get {
                return ResourceManager.GetString("ErrorAccountNotActivelicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario administrador debe tener una licencia asignada..
        /// </summary>
        public static string ErrorAdminLicensesNotAssaigned {
            get {
                return ResourceManager.GetString("ErrorAdminLicensesNotAssaigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id de la función de agregación &apos;{0}&apos; no es válida.
        /// </summary>
        public static string ErrorAggregateFunctionIdInvalid {
            get {
                return ResourceManager.GetString("ErrorAggregateFunctionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Aggregate Functions..
        /// </summary>
        public static string ErrorAggregateFunctionNotFound {
            get {
                return ResourceManager.GetString("ErrorAggregateFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de analysis services: {0}.
        /// </summary>
        public static string ErrorAnalysisServices {
            get {
                return ResourceManager.GetString("ErrorAnalysisServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el ciclo de aprobación.
        /// </summary>
        public static string ErrorApprovalCycleNotFound {
            get {
                return ResourceManager.GetString("ErrorApprovalCycleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo ya se encuentra asignado en el ciclo de aprobación: [{0}].
        /// </summary>
        public static string ErrorApprovalCyclesModelFound {
            get {
                return ResourceManager.GetString("ErrorApprovalCyclesModelFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha actual no se encuentra entre el rango de fechas del BFP.
        /// </summary>
        public static string ErrorBPFDateRange {
            get {
                return ResourceManager.GetString("ErrorBPFDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el BPF.
        /// </summary>
        public static string ErrorBPFNotFound {
            get {
                return ResourceManager.GetString("ErrorBPFNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha actual no se encuentra entre el rango de fechas de la tarea.
        /// </summary>
        public static string ErrorBPFTaskDateNowRange {
            get {
                return ResourceManager.GetString("ErrorBPFTaskDateNowRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los parámetros son requeridos. La tarea que desea ejecutar no tiene asociado parámetros. .
        /// </summary>
        public static string ErrorBPFTaskParametersRequired {
            get {
                return ResourceManager.GetString("ErrorBPFTaskParametersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se detectaron errores en las reglas de negocio.
        /// </summary>
        public static string ErrorBussinesRules {
            get {
                return ResourceManager.GetString("ErrorBussinesRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clausula where inválida: {0}.
        /// </summary>
        public static string ErrorClauseWhereInvalidArgs {
            get {
                return ResourceManager.GetString("ErrorClauseWhereInvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ingresado un código Inválido..
        /// </summary>
        public static string ErrorCodeInvalid {
            get {
                return ResourceManager.GetString("ErrorCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La colección no ha sido instanciada. Verifique el constructor de su entidad..
        /// </summary>
        public static string ErrorCollectionNotInitiated {
            get {
                return ResourceManager.GetString("ErrorCollectionNotInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna con la cual se va a mostrar el valor no existe.
        /// </summary>
        public static string ErrorColumnHasNotValue {
            get {
                return ResourceManager.GetString("ErrorColumnHasNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la columna &apos;IsReal&apos;.
        /// </summary>
        public static string ErrorColumnIsRealNotFound {
            get {
                return ResourceManager.GetString("ErrorColumnIsRealNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, nombre de columna inválido. La tabla PadreHijo no puede tener nombres de columnas reservados como NivelX, donde &quot;X&quot; sea un número.
        /// </summary>
        public static string ErrorColumnLevelNameInvalid {
            get {
                return ResourceManager.GetString("ErrorColumnLevelNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, nombre de columna inválido. No puede utilizar nombres reservados de columnas que son utilizadas para el Log.
        /// </summary>
        public static string ErrorColumnModelLogNameInvalid {
            get {
                return ResourceManager.GetString("ErrorColumnModelLogNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error nombre de columna inválido.
        /// </summary>
        public static string ErrorColumnNameInvalid {
            get {
                return ResourceManager.GetString("ErrorColumnNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la columna inválida: {0}.
        /// </summary>
        public static string ErrorColumnNameInvalidArgs {
            get {
                return ResourceManager.GetString("ErrorColumnNameInvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tabla no puede tener mas de una columna padre.
        /// </summary>
        public static string ErrorColumnParentDuplicate {
            get {
                return ResourceManager.GetString("ErrorColumnParentDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la columna Padre.
        /// </summary>
        public static string ErrorColumnParentNotFound {
            get {
                return ResourceManager.GetString("ErrorColumnParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la columna &apos;IsCalculated&apos;.
        /// </summary>
        public static string ErrorColumnsIsCalculatedNotFound {
            get {
                return ResourceManager.GetString("ErrorColumnsIsCalculatedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la cadena de conexión.
        /// </summary>
        public static string ErrorConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ErrorConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron los valores del contexto global.
        /// </summary>
        public static string ErrorContextGlobalValuesNotFound {
            get {
                return ResourceManager.GetString("ErrorContextGlobalValuesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales ingresadas no son válidas..
        /// </summary>
        public static string ErrorCredentialsInvalid {
            get {
                return ResourceManager.GetString("ErrorCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el DAP.
        /// </summary>
        public static string ErrorDapNotFound {
            get {
                return ResourceManager.GetString("ErrorDapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró un DAP para el usuario.
        /// </summary>
        public static string ErrorDapNotFoundForUser {
            get {
                return ResourceManager.GetString("ErrorDapNotFoundForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo chequear si la base de datos está en línea.
        /// </summary>
        public static string ErrorDatabaseCheckOnline {
            get {
                return ResourceManager.GetString("ErrorDatabaseCheckOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de base de datos inválida.
        /// </summary>
        public static string ErrorDataBaseNameInvalid {
            get {
                return ResourceManager.GetString("ErrorDataBaseNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ya existe en la base de datos..
        /// </summary>
        public static string ErrorDataBaseRegisterExist {
            get {
                return ResourceManager.GetString("ErrorDataBaseRegisterExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se detectaron errores en los valores de entrada.
        /// </summary>
        public static string ErrorDataEntryValues {
            get {
                return ResourceManager.GetString("ErrorDataEntryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema de integridad referencial con el campo {0} en la entidad {1}.
        /// </summary>
        public static string ErrorDataIntegrity {
            get {
                return ResourceManager.GetString("ErrorDataIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos inválidos.
        /// </summary>
        public static string ErrorDataInvalid {
            get {
                return ResourceManager.GetString("ErrorDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lista de datos no puede ser null o vacia.
        /// </summary>
        public static string ErrorDataListEmpty {
            get {
                return ResourceManager.GetString("ErrorDataListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la regla de datos.
        /// </summary>
        public static string ErrorDataRuleNotFound {
            get {
                return ResourceManager.GetString("ErrorDataRuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil de la regla de datos no tiene columnas.
        /// </summary>
        public static string ErrorDataRuleProfileHasNotColumns {
            get {
                return ResourceManager.GetString("ErrorDataRuleProfileHasNotColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil de la regla de datos tiene mas de una columna valor.
        /// </summary>
        public static string ErrorDataRuleProfileMaxValueColumn {
            get {
                return ResourceManager.GetString("ErrorDataRuleProfileMaxValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el perfil de la regla de datos.
        /// </summary>
        public static string ErrorDataRuleProfileNotFound {
            get {
                return ResourceManager.GetString("ErrorDataRuleProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una ejecución programada asociada a la regla de datos. No se puede borrar.
        /// </summary>
        public static string ErrorDataRuleScheduleExist {
            get {
                return ResourceManager.GetString("ErrorDataRuleScheduleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una ejecución programada asociada a la regla de datos. No se puede borrar.
        /// </summary>
        public static string ErrorDataRuleScheduleJobExist {
            get {
                return ResourceManager.GetString("ErrorDataRuleScheduleJobExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Data Types..
        /// </summary>
        public static string ErrorDataTypeNotFound {
            get {
                return ResourceManager.GetString("ErrorDataTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Fecha hasta&apos; debe ser mayor o igual que &apos;fecha desde&apos;.
        /// </summary>
        public static string ErrorDateFromIsGreaterDateTo {
            get {
                return ResourceManager.GetString("ErrorDateFromIsGreaterDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontraron dependencias: .
        /// </summary>
        public static string ErrorDependeciesFound {
            get {
                return ResourceManager.GetString("ErrorDependeciesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dimensión incorrecto. Este proceso solo es para las Dimensiones de Tiempo.
        /// </summary>
        public static string ErrorDimensionTypeNotTime {
            get {
                return ResourceManager.GetString("ErrorDimensionTypeNotTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tabla ya tiene datos cargados y no se puede expandir en horas.
        /// </summary>
        public static string ErrorDimTimeCannotExpandIntoHoursByData {
            get {
                return ResourceManager.GetString("ErrorDimTimeCannotExpandIntoHoursByData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe, en la tabla time, la columna de &apos;horas&apos;.
        /// </summary>
        public static string ErrorDimTimeColumnHoursNotFound {
            get {
                return ResourceManager.GetString("ErrorDimTimeColumnHoursNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La direccion de email &apos;{0}&apos; ya se encuentra registrada. Puede recupar su contraseña para ingresar nuevamente al sistema..
        /// </summary>
        public static string ErrorEmailCurrentRegistered {
            get {
                return ResourceManager.GetString("ErrorEmailCurrentRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo ya existe.
        /// </summary>
        public static string ErrorEmailExists {
            get {
                return ResourceManager.GetString("ErrorEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección de email &apos;{0}&apos; es incorrecta..
        /// </summary>
        public static string ErrorEmailIncorrect {
            get {
                return ResourceManager.GetString("ErrorEmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email no corresponde a un usuario registrado..
        /// </summary>
        public static string ErrorEmailNotCorrespondToRegisteredUser {
            get {
                return ResourceManager.GetString("ErrorEmailNotCorrespondToRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Email Inválido.
        /// </summary>
        public static string ErrorEmailNotValid {
            get {
                return ResourceManager.GetString("ErrorEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro Port debe tener un valor.
        /// </summary>
        public static string ErrorEmailPort {
            get {
                return ResourceManager.GetString("ErrorEmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro SMTPServer debe tener un valor.
        /// </summary>
        public static string ErrorEmailSmtpServer {
            get {
                return ResourceManager.GetString("ErrorEmailSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es requerido.
        /// </summary>
        public static string ErrorFieldIsRequired {
            get {
                return ResourceManager.GetString("ErrorFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con el tamaño (máximo y mínimo) del campo.
        /// </summary>
        public static string ErrorFieldMaximumMinimumLength {
            get {
                return ResourceManager.GetString("ErrorFieldMaximumMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño máximo para el archivo es de {0} mb..
        /// </summary>
        public static string ErrorFileNotValid {
            get {
                return ResourceManager.GetString("ErrorFileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error, no se pudo procesar el archivo.
        /// </summary>
        public static string ErrorFileProcess {
            get {
                return ResourceManager.GetString("ErrorFileProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de filtro {0} no existe.
        /// </summary>
        public static string ErrorFilterTypeNotExists {
            get {
                return ResourceManager.GetString("ErrorFilterTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error..
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro que intenta editar no existe o no está disponible..
        /// </summary>
        public static string ErrorEntityNotFoundForUpdate {
            get {
                return ResourceManager.GetString("ErrorEntityNotFoundForUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error interno.
        /// </summary>
        public static string ErrorGenericInternal {
            get {
                return ResourceManager.GetString("ErrorGenericInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos.
        /// </summary>
        public static string ErrorGenericPermission {
            get {
                return ResourceManager.GetString("ErrorGenericPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al recuperar los datos.
        /// </summary>
        public static string ErrorGenericRetrieveData {
            get {
                return ResourceManager.GetString("ErrorGenericRetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar los datos.
        /// </summary>
        public static string ErrorGenericSaveData {
            get {
                return ResourceManager.GetString("ErrorGenericSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el grupo.
        /// </summary>
        public static string ErrorGroupNotFound {
            get {
                return ResourceManager.GetString("ErrorGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se podrá crear la jerarquía {0}, ya que no se encontró la columna {1}. El problema puede ser que no exista la columna o que exista pero aún no se haya guardado en Analysis Services previamente..
        /// </summary>
        public static string ErrorHierarchyColumnNotFound {
            get {
                return ResourceManager.GetString("ErrorHierarchyColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave incorrecta. Le quedan {0} intentos antes de que la cuenta sea bloqueada..
        /// </summary>
        public static string ErrorInputPasswordWrong {
            get {
                return ResourceManager.GetString("ErrorInputPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La expresión cron no es válida.
        /// </summary>
        public static string ErrorInvalidCronExpression {
            get {
                return ResourceManager.GetString("ErrorInvalidCronExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operación inválida: {0}.
        /// </summary>
        public static string ErrorInvalidOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede establecer una cantidad de licencias menor debido a que ya hay usuarios asignados y utilizando licencias. Primero debería quitarles las licencias a [{0}] 
        ///usuario/s que usted considere. Luego, podrá volver aquí a bajar la cantidad de licencias asignadas al Tenant.
        /// </summary>
        public static string ErrorLicenseAmountAssign {
            get {
                return ResourceManager.GetString("ErrorLicenseAmountAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licencia ha expirado.
        /// </summary>
        public static string ErrorLicenseExpired {
            get {
                return ResourceManager.GetString("ErrorLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de licencias insuficientes..
        /// </summary>
        public static string ErrorLicensesAmount {
            get {
                return ResourceManager.GetString("ErrorLicensesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontró conceptos medida siendo utilizados en más de un modelo.
        /// </summary>
        public static string ErrorMeasuresConceptIdDuplicated {
            get {
                return ResourceManager.GetString("ErrorMeasuresConceptIdDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo tiene asociado dimensiones repetidas.
        /// </summary>
        public static string ErrorModelDimensionDuplicate {
            get {
                return ResourceManager.GetString("ErrorModelDimensionDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo no puede estar relacionado con una dimensión más de una vez.
        /// </summary>
        public static string ErrorModelDimensionRelationshipDuplicate {
            get {
                return ResourceManager.GetString("ErrorModelDimensionRelationshipDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el modelo.
        /// </summary>
        public static string ErrorModelNotFound {
            get {
                return ResourceManager.GetString("ErrorModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ModeType que estas queriendo utilizar no está disponible para ser utilizado en una base de datos en el entorno actual de Analysis Services que tenemos.
        /// </summary>
        public static string ErrorModeTypeNotAvailable {
            get {
                return ResourceManager.GetString("ErrorModeTypeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeType no encontrado.
        /// </summary>
        public static string ErrorModeTypeNotFound {
            get {
                return ResourceManager.GetString("ErrorModeTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el nodo.
        /// </summary>
        public static string ErrorNodeNotFound {
            get {
                return ResourceManager.GetString("ErrorNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fueron encontrados los usuarios para enviar las notificaciones.
        /// </summary>
        public static string ErrorNotificationUsersNotFound {
            get {
                return ResourceManager.GetString("ErrorNotificationUsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error, el objeto ya ha sido modificado (Optimistic concurrency failure)..
        /// </summary>
        public static string ErrorObjectHasBeenUpdated {
            get {
                return ResourceManager.GetString("ErrorObjectHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron opciones válidas.
        /// </summary>
        public static string ErrorOptionsValidNotFound {
            get {
                return ResourceManager.GetString("ErrorOptionsValidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontar el parámetro {0}.
        /// </summary>
        public static string ErrorParameterNotFound {
            get {
                return ResourceManager.GetString("ErrorParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parametro [{0}] no existe.
        /// </summary>
        public static string ErrorParamNotExists {
            get {
                return ResourceManager.GetString("ErrorParamNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los parámetros estan siendo utilizados.
        /// </summary>
        public static string ErrorParamsUsed {
            get {
                return ResourceManager.GetString("ErrorParamsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar el padre con código [{0}].
        /// </summary>
        public static string ErrorParentCodeNotFound {
            get {
                return ResourceManager.GetString("ErrorParentCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Confirmar Nueva Password es requerido.
        /// </summary>
        public static string ErrorPasswordConfirmIsRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordConfirmIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nuevo password ingresado no coincide con su confirmación.
        /// </summary>
        public static string ErrorPasswordConfirmNotMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordConfirmNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        public static string ErrorPasswordIncorrect {
            get {
                return ResourceManager.GetString("ErrorPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener un largo mínimo de {0} caracteres..
        /// </summary>
        public static string ErrorPasswordMinLength2 {
            get {
                return ResourceManager.GetString("ErrorPasswordMinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos un caracter no alfanumérico..
        /// </summary>
        public static string ErrorPasswordMustHaveAnNonAlphanumericCharacter {
            get {
                return ResourceManager.GetString("ErrorPasswordMustHaveAnNonAlphanumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos un dígito (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string ErrorPasswordMustHaveDigits {
            get {
                return ResourceManager.GetString("ErrorPasswordMustHaveDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos 6 caracteres diferentes..
        /// </summary>
        public static string ErrorPassworMustHaveDiferentsCharacters {
            get {
                return ResourceManager.GetString("ErrorPassworMustHaveDiferentsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos una letra minúscula (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string ErrorPassworMustHaveLowercaseCharacter {
            get {
                return ResourceManager.GetString("ErrorPassworMustHaveLowercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe incluir al menos una letra MAYÚSCULA (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string ErrorPassworMustHaveUppercaseCharacter {
            get {
                return ResourceManager.GetString("ErrorPassworMustHaveUppercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Telefono no cumple con la cantidad {0} de &apos;{1}&apos; digitos..
        /// </summary>
        public static string ErrorPhoneNotValid {
            get {
                return ResourceManager.GetString("ErrorPhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con el manejo de PK..
        /// </summary>
        public static string ErrorPk {
            get {
                return ResourceManager.GetString("ErrorPk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El prefijo ingresado no es único.
        /// </summary>
        public static string ErrorPrefixNotUnique {
            get {
                return ResourceManager.GetString("ErrorPrefixNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna {0} no existe en los datos proporcionados..
        /// </summary>
        public static string ErrorProvidedDataColumnNotExists {
            get {
                return ResourceManager.GetString("ErrorProvidedDataColumnNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno de los campos existe en los datos proporcionados..
        /// </summary>
        public static string ErrorProvidedDataFieldsNotExists {
            get {
                return ResourceManager.GetString("ErrorProvidedDataFieldsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error, no se pudo generar la vista Razor.
        /// </summary>
        public static string ErrorRazorGenerate {
            get {
                return ResourceManager.GetString("ErrorRazorGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la relación ya existe.
        /// </summary>
        public static string ErrorRelationshipNameExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un ciclo de aprobación que está utilizando una relación del modelo. No se puede modificar.
        /// </summary>
        public static string ErrorRelationshipsApprovalCycleExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipsApprovalCycleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un Flujo de proceso de negocio que utiliza la relación del modelo. No se puede modificar.
        /// </summary>
        public static string ErrorRelationshipsBpfExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipsBpfExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe valores de contexto global que utilizan la relación del modelo. No se puede modificar.
        /// </summary>
        public static string ErrorRelationshipsCgvExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipsCgvExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un perfil de acceso de datos que utiliza la relación del modelo. No se puede modificar.
        /// </summary>
        public static string ErrorRelationshipsDapExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipsDapExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaciones con nombre de tabla o columna inválida.
        /// </summary>
        public static string ErrorRelationshipsInvalid {
            get {
                return ResourceManager.GetString("ErrorRelationshipsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe una Vista creada, no se pueden modificar las relaciones del modelo.
        /// </summary>
        public static string ErrorRelationshipsViewExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipsViewExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener la información requerida..
        /// </summary>
        public static string ErrorRequiredInfoGet {
            get {
                return ResourceManager.GetString("ErrorRequiredInfoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de rol &apos;{0}&apos; ya existe..
        /// </summary>
        public static string ErrorRoleNameExists {
            get {
                return ResourceManager.GetString("ErrorRoleNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de rol &apos;{0}&apos; es inválido..
        /// </summary>
        public static string ErrorRoleNameInvalid {
            get {
                return ResourceManager.GetString("ErrorRoleNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de SQL Server: {0}.
        /// </summary>
        public static string ErrorSqlServer {
            get {
                return ResourceManager.GetString("ErrorSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado ingresado no existe.
        /// </summary>
        public static string ErrorStatusSubmittedNotExists {
            get {
                return ResourceManager.GetString("ErrorStatusSubmittedNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la tabla existe.
        /// </summary>
        public static string ErrorTableNameExists {
            get {
                return ResourceManager.GetString("ErrorTableNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error nombre de tabla inválido.
        /// </summary>
        public static string ErrorTableNameInvalid {
            get {
                return ResourceManager.GetString("ErrorTableNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de tabla inválido: {0}.
        /// </summary>
        public static string ErrorTableNameInvalidArgs {
            get {
                return ResourceManager.GetString("ErrorTableNameInvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  La tabla no existe en la base de datos.
        /// </summary>
        public static string ErrorTableNotExitsInDataBase {
            get {
                return ResourceManager.GetString("ErrorTableNotExitsInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la tabla.
        /// </summary>
        public static string ErrorTableNotFound {
            get {
                return ResourceManager.GetString("ErrorTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de tabla debe ser &quot;Provider&quot; o &quot;M&quot;.
        /// </summary>
        public static string ErrorTableType {
            get {
                return ResourceManager.GetString("ErrorTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tabla incorrecta. Este proceso solo es para los Modelos.
        /// </summary>
        public static string ErrorTableTypeNotModel {
            get {
                return ResourceManager.GetString("ErrorTableTypeNotModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una base de datos activa en el tenant..
        /// </summary>
        public static string ErrorTenantDBNotFound {
            get {
                return ResourceManager.GetString("ErrorTenantDBNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Tenant ya existe.
        /// </summary>
        public static string ErrorTenantExists {
            get {
                return ResourceManager.GetString("ErrorTenantExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tenant es root..
        /// </summary>
        public static string ErrorTenantIsRoot {
            get {
                return ResourceManager.GetString("ErrorTenantIsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tenant no está activo.
        /// </summary>
        public static string ErrorTenantNotActive {
            get {
                return ResourceManager.GetString("ErrorTenantNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el tenant.
        /// </summary>
        public static string ErrorTenantNotFound {
            get {
                return ResourceManager.GetString("ErrorTenantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error tenant no root.
        /// </summary>
        public static string ErrorTenantNotRoot {
            get {
                return ResourceManager.GetString("ErrorTenantNotRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden hacer modificaciones de información sin un tenant asignado.
        /// </summary>
        public static string ErrorTenantNotSelected {
            get {
                return ResourceManager.GetString("ErrorTenantNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la columna que indica la granularidad del Modelo.
        /// </summary>
        public static string ErrorTimeColumnGranularityNotFound {
            get {
                return ResourceManager.GetString("ErrorTimeColumnGranularityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error con el manejo de UK..
        /// </summary>
        public static string ErrorUKManage {
            get {
                return ResourceManager.GetString("ErrorUKManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya es parte del rol &apos;{0}&apos;..
        /// </summary>
        public static string ErrorUserBelongsRole {
            get {
                return ResourceManager.GetString("ErrorUserBelongsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El bloqueo no está habilitado para este usuario..
        /// </summary>
        public static string ErrorUserBlockingNotEnable {
            get {
                return ResourceManager.GetString("ErrorUserBlockingNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya existe en la base de datos..
        /// </summary>
        public static string ErrorUserExists {
            get {
                return ResourceManager.GetString("ErrorUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya tiene contraseña..
        /// </summary>
        public static string ErrorUserHavePassword {
            get {
                return ResourceManager.GetString("ErrorUserHavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un usuario con ese nombre ya existe..
        /// </summary>
        public static string ErrorUserNameExist {
            get {
                return ResourceManager.GetString("ErrorUserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;{0}&apos; ya existe, por favor ingrese un nombre diferente..
        /// </summary>
        public static string ErrorUserNameExistUseNewOne {
            get {
                return ResourceManager.GetString("ErrorUserNameExistUseNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario &apos;{0}&apos; es inválido. Solo puede contener letras y números..
        /// </summary>
        public static string ErrorUserNameInvalid {
            get {
                return ResourceManager.GetString("ErrorUserNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario logueado no tiene privilegios para modificar los datos del tenant de un usuario ..
        /// </summary>
        public static string ErrorUserNoPrivilegesChangeTenantData {
            get {
                return ResourceManager.GetString("ErrorUserNoPrivilegesChangeTenantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, no tiene permiso para ver Usuario seleccionado.
        /// </summary>
        public static string ErrorUserNoPrivilegesViewUserSelected {
            get {
                return ResourceManager.GetString("ErrorUserNoPrivilegesViewUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no es parte del rol &apos;{0}&apos;..
        /// </summary>
        public static string ErrorUserNotBelongsRole {
            get {
                return ResourceManager.GetString("ErrorUserNotBelongsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar el usuario.
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos para acceder a esta funcionalidad.
        /// </summary>
        public static string ErrorUserNotPrivilegesAccess {
            get {
                return ResourceManager.GetString("ErrorUserNotPrivilegesAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y Clave son requeridos..
        /// </summary>
        public static string ErrorUserPassRequired {
            get {
                return ResourceManager.GetString("ErrorUserPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error, no se pudo recuperar el usuario o el mismo no tiene los permisos suficientes..
        /// </summary>
        public static string ErrorUserRecuparate {
            get {
                return ResourceManager.GetString("ErrorUserRecuparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validation.
        /// </summary>
        public static string ErrorValidation {
            get {
                return ResourceManager.GetString("ErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los IDs objetivo son requeridos.
        /// </summary>
        public static string ErrorValueTargetIdIsRequired {
            get {
                return ResourceManager.GetString("ErrorValueTargetIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la Vista.
        /// </summary>
        public static string ErrorViewNotFound {
            get {
                return ResourceManager.GetString("ErrorViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-confirmación de cuenta.
        /// </summary>
        public static string ReconfirmAccount {
            get {
                return ResourceManager.GetString("ReconfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de inicio de sesión para el usuario..
        /// </summary>
        public static string SqlError18456 {
            get {
                return ResourceManager.GetString("SqlError18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del objeto es inválido..
        /// </summary>
        public static string SqlError208 {
            get {
                return ResourceManager.GetString("SqlError208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede insertar un valor duplicado..
        /// </summary>
        public static string SqlError2627 {
            get {
                return ResourceManager.GetString("SqlError2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede abrir la base de datos solicitada..
        /// </summary>
        public static string SqlError4060 {
            get {
                return ResourceManager.GetString("SqlError4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede insertar un valor NULL en una columna que no acepta valores NULL..
        /// </summary>
        public static string SqlError515 {
            get {
                return ResourceManager.GetString("SqlError515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el registro porque está siendo referenciado por otro registro.
        /// </summary>
        public static string SqlError547 {
            get {
                return ResourceManager.GetString("SqlError547", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de cadena o binarios serían truncados..
        /// </summary>
        public static string SqlError8152 {
            get {
                return ResourceManager.GetString("SqlError8152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error en la base de datos..
        /// </summary>
        public static string SqlErrorDefault {
            get {
                return ResourceManager.GetString("SqlErrorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error desconocido..
        /// </summary>
        public static string SqlErrorUnknown {
            get {
                return ResourceManager.GetString("SqlErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se confirmo la cuenta {0}. Ingrese Usuario y Contraseña para iniciar sesión..
        /// </summary>
        public static string SuccessAccountConfirm {
            get {
                return ResourceManager.GetString("SuccessAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta ya ha sido confirmada.
        /// </summary>
        public static string SuccessAccountConfirm2 {
            get {
                return ResourceManager.GetString("SuccessAccountConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se completo el cambio de clave de la cuenta {0}. Complete los campos para ingresar..
        /// </summary>
        public static string SuccessPasswordReset {
            get {
                return ResourceManager.GetString("SuccessPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos una columna debe ser Unique..
        /// </summary>
        public static string WarnColumnUnique {
            get {
                return ResourceManager.GetString("WarnColumnUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima para el campo &apos;{0}&apos; es de {1} caracteres..
        /// </summary>
        public static string WarnFieldMaxLength {
            get {
                return ResourceManager.GetString("WarnFieldMaxLength", resourceCulture);
            }
        }
    }
}
