-- =====================================================================
-- AcgFotos API - Seed de la base de TESTS (AcgFotos_Tests)
-- =====================================================================
-- Se ejecuta despues de cada Respawn reset (tablas vacias), por eso NO usa
-- IF NOT EXISTS: es un unico batch que se corre con un NpgsqlCommand.
--
-- Password en claro de TODOS los usuarios sembrados: Root@AcgFotos2026!
-- (mismo PasswordHash que el seed de dev, PBKDF2-SHA256 formato Identity v3).
--
-- Identificadores en minuscula sin comillas (UseLowerCaseNamingConvention,
-- ver DatabaseFactory/AcgFotosDbContext): Postgres pliega cualquier
-- identificador sin comillas a minuscula, asi que da igual el case con el
-- que se escriban acá — coinciden igual con las tablas/columnas reales.
-- Sin SET IDENTITY_INSERT (no existe en Postgres): las columnas identity acá
-- son GENERATED BY DEFAULT, que permite insertar un valor explícito sin nada
-- especial (a diferencia de SQL Server, que lo bloquea salvo IDENTITY_INSERT).
--
-- Modelo de datos pensado para los casos de Auth (110-auth.md):
--   - Tenant 1 = root (RootTenantId=1, activo)         -> usuarios root => isRoot=true
--   - Tenant 2 = activo                                -> usuarios no-root reales (isRoot=false)
--   - Tenant 3 = INACTIVO                              -> guarda de tenant inactivo
--   Usuarios:
--     1  root     (t1, Administrador, isRoot)          -> AUTH-01, AUTH-16, fuente de impersonacion
--     10 userb    (t2, no-root, EmailConfirmed, licencia activa) -> AUTH-02 (isRoot=false)
--     11 adminb   (t3 inactivo, Administrador, licencia activa)  -> AUTH-13 (admin ignora tenant inactivo)
--     12 userc    (t3 inactivo, no-root)               -> AUTH-12 / AUTH-29 (no-root en tenant inactivo)
-- =====================================================================

-- Aplicacion (FK de Permisos y Parametros) --------------------------------
INSERT INTO gen_Aplicaciones (Id, Codigo, Nombre, Activo, Icono, IconoUrl)
VALUES (1, 'general', 'General', true, 'home', NULL);

-- Permiso root (FK de Parametros) -----------------------------------------
INSERT INTO gen_Permisos (Id, Nombre, CodigoPermiso, Descripcion, Activo, PermisoPadreId, AplicacionId, EsRestringido)
VALUES (1, 'PermisoRoot', 'PermisoRoot', 'Permiso root', true, NULL, 1, true);

-- Tenants -----------------------------------------------------------------
INSERT INTO gen_Tenants (Id, Codigo, Nombre, Activo, DarkModeByDefault, TipoLayoutLogin, LogoLoginLightUrl, LogoLoginDarkUrl, LogoHeaderLightUrl, LogoHeaderDarkUrl, FaviconUrl, ErrorDescription, HasError)
VALUES
    (1, 'root',     'root',     true,  false, 0, '', '', '', '', '', '', false),
    (2, 'tenant-b', 'Tenant B', true,  false, 0, '', '', '', '', '', '', false),
    (3, 'tenant-c', 'Tenant C', false, false, 0, '', '', '', '', '', '', false);

-- TipoLicencia ------------------------------------------------------------
INSERT INTO gen_TipoLicencia (Id, Descripcion, CodigoTipoLicencia, EsDefaultParaNuevoTenant)
VALUES
    (1, 'Visualizador',             'ofDataReader', false),
    (2, 'Admin del Tenant Cliente', 'adminCliente', true);

-- Roles -------------------------------------------------------------------
INSERT INTO gen_Roles (Id, Descripcion, EsDefaultParaNuevoTenant)
VALUES (1, 'Administrador', false);

-- Usuarios ----------------------------------------------------------------
INSERT INTO gen_Usuarios
    (Id, TenantId, Nombre, Apellido, Telefono, Administrador, TokenExpirationDate, DateCreated, FechaCambioClave, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnd, LockoutEnabled, AccessFailedCount, ProfilePicture)
VALUES
    (1,  1, 'root',    'root', 1234567891, true,  '2099-12-31T00:00:00', '2001-01-01T00:00:00', '2001-01-01T00:00:00', 'root',    'ROOT',    'admin@tech-bi.com',    'ADMIN@TECH-BI.COM',    true,  'AQAAAAIAAYagAAAAEBrKnVSPJbU1wjiSQLP141pc8bQRIuttqdu0dBRmkVnYsyy5Zm3SdYs9z35wxWpvLw==', 'OEVZTCZGXK5BQTG2JM2AZOED7V3NHQTK', '1858f640-3f6c-49f6-92e9-d0a9ffb39970', NULL, false, false, NULL, false, 0, NULL),
    (10, 2, 'User',    'B',    1122334455, false, '2099-12-31T00:00:00', '2024-01-01T00:00:00', '2024-01-01T00:00:00', 'userb',   'USERB',   'userb@tech-bi.com',    'USERB@TECH-BI.COM',    true,  'AQAAAAIAAYagAAAAEBrKnVSPJbU1wjiSQLP141pc8bQRIuttqdu0dBRmkVnYsyy5Zm3SdYs9z35wxWpvLw==', 'USERB-STAMP-0000000000000000001', 'userb-concurrency-0001', NULL, false, false, NULL, true, 0, NULL),
    (11, 3, 'Admin',   'B',    1122334466, true,  '2099-12-31T00:00:00', '2024-01-01T00:00:00', '2024-01-01T00:00:00', 'adminb',  'ADMINB',  'adminb@tech-bi.com',   'ADMINB@TECH-BI.COM',   true,  'AQAAAAIAAYagAAAAEBrKnVSPJbU1wjiSQLP141pc8bQRIuttqdu0dBRmkVnYsyy5Zm3SdYs9z35wxWpvLw==', 'ADMINB-STAMP-000000000000000001', 'adminb-concurrency-0001', NULL, false, false, NULL, true, 0, NULL),
    (12, 3, 'User',    'C',    1122334477, false, '2099-12-31T00:00:00', '2024-01-01T00:00:00', '2024-01-01T00:00:00', 'userc',   'USERC',   'userc@tech-bi.com',    'USERC@TECH-BI.COM',    true,  'AQAAAAIAAYagAAAAEBrKnVSPJbU1wjiSQLP141pc8bQRIuttqdu0dBRmkVnYsyy5Zm3SdYs9z35wxWpvLw==', 'USERC-STAMP-0000000000000000001', 'userc-concurrency-0001', NULL, false, false, NULL, true, 0, NULL),
    -- pending (13): cuenta sin confirmar y SIN password -> confirmar-cuenta happy path (AUTH-51).
    (13, 2, 'Pending', 'User', 1122334488, false, '2099-12-31T00:00:00', '2024-01-01T00:00:00', '2024-01-01T00:00:00', 'pending', 'PENDING', 'pending@tech-bi.com',   'PENDING@TECH-BI.COM',   false, NULL,                                                                                       'PENDING-STAMP-00000000000000001', 'pending-concurrency-001', NULL, false, false, NULL, true, 0, NULL),
    -- userb2 (14): segundo no-root en tenant 2 -> re-impersonar (AUTH-75) y aislamiento multi-tenant.
    (14, 2, 'User',    'B2',   1122334499, false, '2099-12-31T00:00:00', '2024-01-01T00:00:00', '2024-01-01T00:00:00', 'userb2',  'USERB2',  'userb2@tech-bi.com',   'USERB2@TECH-BI.COM',   true,  'AQAAAAIAAYagAAAAEBrKnVSPJbU1wjiSQLP141pc8bQRIuttqdu0dBRmkVnYsyy5Zm3SdYs9z35wxWpvLw==', 'USERB2-STAMP-000000000000000001', 'userb2-concurrency-0001', NULL, false, false, NULL, true, 0, NULL),
    -- adminb2 (15): ADMIN del tenant 2 (Administrador=true) -> set-administrador, search excluye-admin, ops admin-only.
    (15, 2, 'Admin',   'B2',   1122334400, true,  '2099-12-31T00:00:00', '2024-01-01T00:00:00', '2024-01-01T00:00:00', 'adminb2', 'ADMINB2', 'adminb2@tech-bi.com',  'ADMINB2@TECH-BI.COM',  true,  'AQAAAAIAAYagAAAAEBrKnVSPJbU1wjiSQLP141pc8bQRIuttqdu0dBRmkVnYsyy5Zm3SdYs9z35wxWpvLw==', 'ADMINB2-STAMP-00000000000000001', 'adminb2-concurrency-001', NULL, false, false, NULL, true, 0, NULL);

-- Cupos de licencia por tenant (TenantLicencia) ---------------------------
INSERT INTO gen_TenantLicencias (Id, TenantId, TipoLicenciaId, Cantidad, StartDatetime, ExpireDatetime, ModifiedDatetime)
VALUES
    (1, 2, 1, 5, '2024-01-01T00:00:00', '2099-12-31T00:00:00', '2024-01-01T00:00:00'),
    (2, 3, 1, 5, '2024-01-01T00:00:00', '2099-12-31T00:00:00', '2024-01-01T00:00:00');

-- Licencia por usuario (UsuarioTipoLicencia) ------------------------------
INSERT INTO gen_UsuarioTipoLicencia (Id, UsuarioId, TipoLicenciaId, CreatedDatetime, TenantId, IsActive)
VALUES
    (1, 10, 1, '2024-01-01T00:00:00', 2, true),
    (2, 11, 1, '2024-01-01T00:00:00', 3, true),
    (3, 14, 1, '2024-01-01T00:00:00', 2, true),
    (4, 15, 1, '2024-01-01T00:00:00', 2, true);

-- Parametros de Email (Fwk.Email.*): EmailEnabled=false en dev/test (no envia SMTP real),
-- pero la fila Password debe existir (EmailSender.ObtenerParametros lanza si falta).
INSERT INTO gen_Parametros (Id, AplicacionId, PermisoId, TipoDato, Nombre, Descripcion, Valor)
VALUES
    (7,  1, 1, 3, 'Fwk.Email.From',         'GenParamsEmailFrom',     'jkaiter@tech-bi.com'),
    (8,  1, 1, 3, 'Fwk.Email.SMTPServer',   'GenParamsSMTPServer',    'smtp.gmail.com'),
    (9,  1, 1, 1, 'Fwk.Email.Port',         'GenParamsEmailPort',     '587'),
    (10, 1, 1, 3, 'Fwk.Email.User',             'GenParamsEmailUser',         'jkaiter@tech-bi.com'),
    (11, 1, 1, 3, 'Fwk.Email.Password',         'GenParamsEmailPassword',     ''),
    (12, 1, 1, 3, 'Fwk.Email.NombreRemitente',  'GenParamsSenderName',        'Test'),
    (13, 1, 1, 3, 'Fwk.Email.ForceToEmail',     'GenParamsForceToEmail',      'test@yopmail.com'),
    (14, 1, 1, 3, 'Fwk.Email.UseAnonymousLogin','GenParamsUseAnonymousLogin', 'false'),
    (15, 1, 1, 3, 'Fwk.Email.BypassCertificate','GenParamsBypassCertificate', 'false'),
    (16, 1, 1, 3, 'Fwk.Email.ForceTo',          'GenParamsForceTo',           'false'),
    (17, 1, 1, 3, 'Fwk.Email.SSL',              'GenParamsSSL',               'true'),
    (18, 1, 1, 3, 'Fwk.Email.EmailEnabled',     'GenParamsEmailEnabled',      'false');

-- Menus (catalogo global; los RoutePath calzan con app.routes.ts del front) ------------------
-- Todos con PermisoId=1 (PermisoRoot): en dev/tests se opera como root, que arma su menu por ese
-- permiso. El menu curado del fotografo NO-root se define en el alta real del negocio (para verlo,
-- su rol debe recibir el permiso de estos menus, o re-apuntarse los menus a un permiso propio —
-- ver notas abiertas). Ids fijos 100+ para el arbol padre-hijo; los tests que insertan menus
-- propios no fuerzan Id, asi que no hay colision de identity.
INSERT INTO gen_Menus
    (Id, Nombre, Codigo, Estado, ImagenWeb, Orden, MenuPadreId, PermisoId, AplicacionId, VisibleSideMenu, VisibleDash, RoutePath)
VALUES
    -- Vertical Fotos (el negocio, primero)
    (100, 'Fotos',                 'Fotos',                 true, 'photo_camera',          1, NULL, 1, 1, true,  false, NULL),
    (101, 'Eventos',               'FotosEventos',          true, 'event',                 1, 100,  1, 1, true,  true,  '/fotos/eventos'),
    (102, 'Grupos',                'FotosGrupos',           true, 'people',                2, 100,  1, 1, true,  true,  '/fotos/grupos'),
    (104, 'Galería',               'FotosGaleria',          true, 'photo_library',         3, 100,  1, 1, true,  true,  '/fotos/galeria'),
    (105, 'Tarjetas',              'FotosTarjetas',         true, 'qr_code_2',             4, 100,  1, 1, true,  true,  '/fotos/tarjetas'),
    (103, 'Pedidos',               'FotosPedidos',          true, 'receipt_long',          5, 100,  1, 1, true,  true,  '/fotos/pedidos'),
    (106, 'Marca de agua',         'FotosMarcaAgua',        true, 'branding_watermark',    6, 100,  1, 1, true,  false, '/fotos/marca-agua'),
    (107, 'Publicación',           'FotosPublicacion',      true, 'high_quality',          7, 100,  1, 1, true,  false, '/fotos/publicacion'),
    -- Administracion (usuarios/tenants/roles/licencias: lo que pide el alta real del negocio)
    (110, 'Administración',        'Administracion',        true, 'settings',              2, NULL, 1, 1, true,  false, NULL),
    (111, 'Usuarios',              'Usuarios',              true, 'group',                 1, 110,  1, 1, true,  true,  '/usuarios'),
    (112, 'Grupos',                'Grupos',                true, 'groups',                2, 110,  1, 1, true,  false, '/grupos'),
    (113, 'Tenants',               'Tenants',               true, 'other_houses',          3, 110,  1, 1, true,  false, '/tenants'),
    (114, 'Roles',                 'Roles',                 true, 'verified_user',         4, 110,  1, 1, true,  false, '/roles'),
    (115, 'Tipos de licencia',     'TiposLicencias',        true, 'perm_contact_calendar', 5, 110,  1, 1, true,  false, '/tipos-licencias'),
    -- Plataforma (configuracion avanzada del framework)
    (120, 'Plataforma',            'Plataforma',            true, 'settings_applications', 3, NULL, 1, 1, true,  false, NULL),
    (121, 'Menús',                 'Menus',                 true, 'view_list',             1, 120,  1, 1, true,  false, '/menus'),
    (122, 'Permisos',              'Permisos',              true, 'security',              2, 120,  1, 1, true,  false, '/permisos'),
    (123, 'Aplicaciones',          'Aplicaciones',          true, 'web',                   3, 120,  1, 1, true,  false, '/aplicaciones'),
    (124, 'Endpoints',             'Endpoints',             true, 'send',                  4, 120,  1, 1, true,  false, '/endpoints'),
    (125, 'Parámetros',            'Parametros',            true, 'tune',                  5, 120,  1, 1, true,  false, '/parametros'),
    (126, 'Parámetros por tenant', 'ParametroValorTenant',  true, 'tune',                  6, 120,  1, 1, true,  false, '/parametros-valor-tenant'),
    (127, 'Logs',                  'LogInfos',              true, 'list',                  7, 120,  1, 1, true,  false, '/logs'),
    (128, 'Auditoría',             'Auditoria',             true, 'transfer_within_a_station', 8, 120, 1, 1, true, false, '/auditoria');

-- Postgres no resincroniza la secuencia de la identity tras un INSERT con Id explícito (a diferencia
-- de SQL Server, donde IDENTITY_INSERT sí hace avanzar el contador interno): sin esto, el próximo
-- Id "automático" que genere la app durante un test podría repetir uno de los sembrados arriba y
-- violar la PK. Se sincroniza cada secuencia al MAX(Id) realmente sembrado, tabla por tabla.
-- OJO: a diferencia del nombre de tabla (que pg_get_serial_sequence resuelve vía regclass y pliega a
-- minúscula solo), el nombre de columna NO se pliega — tiene que ir literal en minúscula ('id').
SELECT setval(pg_get_serial_sequence('gen_Aplicaciones', 'id'), (SELECT MAX(Id) FROM gen_Aplicaciones));
SELECT setval(pg_get_serial_sequence('gen_Permisos', 'id'), (SELECT MAX(Id) FROM gen_Permisos));
SELECT setval(pg_get_serial_sequence('gen_Tenants', 'id'), (SELECT MAX(Id) FROM gen_Tenants));
SELECT setval(pg_get_serial_sequence('gen_TipoLicencia', 'id'), (SELECT MAX(Id) FROM gen_TipoLicencia));
SELECT setval(pg_get_serial_sequence('gen_Roles', 'id'), (SELECT MAX(Id) FROM gen_Roles));
SELECT setval(pg_get_serial_sequence('gen_Usuarios', 'id'), (SELECT MAX(Id) FROM gen_Usuarios));
SELECT setval(pg_get_serial_sequence('gen_TenantLicencias', 'id'), (SELECT MAX(Id) FROM gen_TenantLicencias));
SELECT setval(pg_get_serial_sequence('gen_UsuarioTipoLicencia', 'id'), (SELECT MAX(Id) FROM gen_UsuarioTipoLicencia));
SELECT setval(pg_get_serial_sequence('gen_Parametros', 'id'), (SELECT MAX(Id) FROM gen_Parametros));
SELECT setval(pg_get_serial_sequence('gen_Menus', 'id'), (SELECT MAX(Id) FROM gen_Menus));
