//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.Database.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.Database.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar Perfil de Regla de datos.
        /// </summary>
        internal static string ExecuteDataRuleProfile {
            get {
                return ResourceManager.GetString("ExecuteDataRuleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interno unicamente..
        /// </summary>
        internal static string InfoAutomaticTooltip {
            get {
                return ResourceManager.GetString("InfoAutomaticTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene datos binarios..
        /// </summary>
        internal static string InfoBinaryTooltip {
            get {
                return ResourceManager.GetString("InfoBinaryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene valores de datos booleanos..
        /// </summary>
        internal static string InfoBooleanTooltip {
            get {
                return ResourceManager.GetString("InfoBooleanTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar perfil de regla de datos.
        /// </summary>
        internal static string InfoBPFActionExecuteDataRuleProfile {
            get {
                return ResourceManager.GetString("InfoBPFActionExecuteDataRuleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar dimensiones.
        /// </summary>
        internal static string InfoBPFActionLoadDimensions {
            get {
                return ResourceManager.GetString("InfoBPFActionLoadDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar datos reales al modelo..
        /// </summary>
        internal static string InfoBPFActionLoadRealDataToModel {
            get {
                return ResourceManager.GetString("InfoBPFActionLoadRealDataToModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir ciclo de aprobación.
        /// </summary>
        internal static string InfoBPFActionOpenApprovalCycle {
            get {
                return ResourceManager.GetString("InfoBPFActionOpenApprovalCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Planilla de carga.
        /// </summary>
        internal static string InfoBPFActionOpenInputForm {
            get {
                return ResourceManager.GetString("InfoBPFActionOpenInputForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir URL.
        /// </summary>
        internal static string InfoBPFActionOpenURL {
            get {
                return ResourceManager.GetString("InfoBPFActionOpenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar correo.
        /// </summary>
        internal static string InfoBPFActionSendEmail {
            get {
                return ResourceManager.GetString("InfoBPFActionSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completo.
        /// </summary>
        internal static string InfoBPFTaskStatusCompleteTooltip {
            get {
                return ResourceManager.GetString("InfoBPFTaskStatusCompleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierto.
        /// </summary>
        internal static string InfoBPFTaskStatusOpenTooltip {
            get {
                return ResourceManager.GetString("InfoBPFTaskStatusOpenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene datos de fecha y hora..
        /// </summary>
        internal static string InfoDateTimeTooltip {
            get {
                return ResourceManager.GetString("InfoDateTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene valores de datos decimales..
        /// </summary>
        internal static string InfoDecimalTooltip {
            get {
                return ResourceManager.GetString("InfoDecimalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una dimensión cuyos atributos representan versiones o reales de una planificación..
        /// </summary>
        internal static string InfoDimTypeCategoryTooltip {
            get {
                return ResourceManager.GetString("InfoDimTypeCategoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una dimensión cuyos atributos representan los valores numéricos de los indicadores de negocio..
        /// </summary>
        internal static string InfoDimTypeConceptTooltip {
            get {
                return ResourceManager.GetString("InfoDimTypeConceptTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este tipo de dimensión contiene datos y metadatos de moneda..
        /// </summary>
        internal static string InfoDimTypeMoneyTooltip {
            get {
                return ResourceManager.GetString("InfoDimTypeMoneyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una dimensión cuyos atributos representan períodos de tiempo, como años, semestres, trimestres, meses y días..
        /// </summary>
        internal static string InfoDimTypeTimeTooltip {
            get {
                return ResourceManager.GetString("InfoDimTypeTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una dimensión cuyo tipo no se ha establecido en un tipo de dimensión especial..
        /// </summary>
        internal static string InfoDimTypeUserDefinedTooltip {
            get {
                return ResourceManager.GetString("InfoDimTypeUserDefinedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene números de punto flotante de doble precisión..
        /// </summary>
        internal static string InfoDoubleTooltip {
            get {
                return ResourceManager.GetString("InfoDoubleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso de datos con una lista desplegable.
        /// </summary>
        internal static string InfoInputTypeDropdownTooltip {
            get {
                return ResourceManager.GetString("InfoInputTypeDropdownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso de datos en campo de texto.
        /// </summary>
        internal static string InfoInputTypeTextboxTooltip {
            get {
                return ResourceManager.GetString("InfoInputTypeTextboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene números enteros..
        /// </summary>
        internal static string InfoInt64Tooltip {
            get {
                return ResourceManager.GetString("InfoInt64Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programar método de tabla de copia por perfil de regla de datos.
        /// </summary>
        internal static string InfoScheduleCopyTablesByDataRuleProfile {
            get {
                return ResourceManager.GetString("InfoScheduleCopyTablesByDataRuleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcula el promedio de valores para todos los miembros secundarios que no están vacíos..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsAverageTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsAverageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devuelve el recuento de filas de la tabla..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsCountTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsCountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La agregación predeterminada es Suma para columnas numéricas. De lo contrario, el valor predeterminado es Ninguno..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsDefaultTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsDefaultTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devuelve el recuento de todos los miembros secundarios únicos..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsDistinctCountTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsDistinctCountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devuelve el valor más alto para todos los miembros secundarios..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsMaxTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsMaxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devuelve el valor más bajo para todos los miembros secundarios..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsMinTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsMinTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deja la función agregada sin especificar..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsNoneTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsNoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcula la suma de los valores contenidos en la columna. Esta es la función de agregación predeterminada..
        /// </summary>
        internal static string InfoSSASAggregateFunctionsSumTooltip {
            get {
                return ResourceManager.GetString("InfoSSASAggregateFunctionsSumTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente de datos estructurados.
        /// </summary>
        internal static string InfoSSASDataSourceTypeMTooltip {
            get {
                return ResourceManager.GetString("InfoSSASDataSourceTypeMTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legado: fuente de datos del proveedor.
        /// </summary>
        internal static string InfoSSASDataSourceTypeProviderTooltip {
            get {
                return ResourceManager.GetString("InfoSSASDataSourceTypeProviderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo las particiones pueden usar este valor. Hereda el DefaultMode del Model.
        /// </summary>
        internal static string InfoSSASModeTypeDefaultTooltip {
            get {
                return ResourceManager.GetString("InfoSSASModeTypeDefaultTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se cargarán en la memoria desde el lago de datos o se consultarán dinámicamente si el fallback de DirectLake está habilitado. Este valor solo se admite cuando el nivel de compatibilidad de la base de datos es 1604 o superior.
        /// </summary>
        internal static string InfoSSASModeTypeDirectLakeTooltip {
            get {
                return ResourceManager.GetString("InfoSSASModeTypeDirectLakeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos serán consultados dinamicamente en el origen de datos.
        /// </summary>
        internal static string InfoSSASModeTypeDirectQueryTooltip {
            get {
                return ResourceManager.GetString("InfoSSASModeTypeDirectQueryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliza Import y DirectQuery para soportar consultar en composite models. Este valor solo se admite cuando el nivel de compatibilidad de la base de datos es 1455 o superior.
        /// </summary>
        internal static string InfoSSASModeTypeDualTooltip {
            get {
                return ResourceManager.GetString("InfoSSASModeTypeDualTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se importarán desde el origen de datos.
        /// </summary>
        internal static string InfoSSASModeTypeImportTooltip {
            get {
                return ResourceManager.GetString("InfoSSASModeTypeImportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No referenciarlo. Interno de Analysis Services..
        /// </summary>
        internal static string InfoSSASModeTypePushTooltip {
            get {
                return ResourceManager.GetString("InfoSSASModeTypePushTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto no es consultable y no contiene datos. Debe ser actualizado para que funcione. Esto se aplica solo a objetos calculados, como columnas calculadas, jerarquías y tablas calculadas..
        /// </summary>
        internal static string InfoSSASObjectStatesCalculationNeededTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesCalculationNeededTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto se encuentra en un estado de error debido a que algunas de sus dependencias de cálculo están en un estado de error. No es consultable..
        /// </summary>
        internal static string InfoSSASObjectStatesDependencyErrorTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesDependencyErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto se encuentra en un estado de error debido a que ocurrió un error durante la evaluación de la expresión. No es consultable..
        /// </summary>
        internal static string InfoSSASObjectStatesEvaluationErrorTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesEvaluationErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunas partes del objeto no tienen datos. Refresca el objeto para agregar el resto de los datos. El objeto es consultable. Esto se aplica a objetos no calculados, como columnas de datos, particiones y tablas..
        /// </summary>
        internal static string InfoSSASObjectStatesIncompleteTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesIncompleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto es consultable pero no contiene datos. Refréscalo para traer los datos. Se aplica a objetos no calculados, como columnas de datos, particiones y tablas.
        /// </summary>
        internal static string InfoSSASObjectStatesNoDataTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesNoDataTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto no ha sido creado aún.
        /// </summary>
        internal static string InfoSSAsObjectStatesNotCreatedTooltip {
            get {
                return ResourceManager.GetString("InfoSSAsObjectStatesNotCreatedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto está actualizado, contiene datos actuales y es consultable..
        /// </summary>
        internal static string InfoSSASObjectStatesReadyTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesReadyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto se encuentra en un estado de error debido a una expresión no válida. No se puede consultar..
        /// </summary>
        internal static string InfoSSASObjectStatesSemanticErrorTooltip {
            get {
                return ResourceManager.GetString("InfoSSASObjectStatesSemanticErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especifica el lado &quot;muchos&quot; de una relación de &quot;uno a muchos&quot;..
        /// </summary>
        internal static string InfoSSASRelationshipEndCardinalityManyTooltip {
            get {
                return ResourceManager.GetString("InfoSSASRelationshipEndCardinalityManyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La relación no está especificada..
        /// </summary>
        internal static string InfoSSASRelationshipEndCardinalityNoneTooltip {
            get {
                return ResourceManager.GetString("InfoSSASRelationshipEndCardinalityNoneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especifica el lado &quot;uno&quot; de una relación &quot;uno a uno&quot; o &quot;uno a muchos&quot;..
        /// </summary>
        internal static string InfoSSASRelationshipEndCardinalityOneTooltip {
            get {
                return ResourceManager.GetString("InfoSSASRelationshipEndCardinalityOneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna o medida contiene valores de datos de cadena..
        /// </summary>
        internal static string InfoStringTooltip {
            get {
                return ResourceManager.GetString("InfoStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inicial de una columna recién creada, reemplazada por un valor real después de guardar una columna en el servidor..
        /// </summary>
        internal static string InfoUnknownTooltip {
            get {
                return ResourceManager.GetString("InfoUnknownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una medida con diferentes tipos de datos..
        /// </summary>
        internal static string InfoVariantTooltip {
            get {
                return ResourceManager.GetString("InfoVariantTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna que puede producir cero o varias columnas, dependiendo de los datos de la planilla de carga y los filtros utilizados..
        /// </summary>
        internal static string InfoViewExcelColumnTypeColumnsMadeFromFiltersTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeColumnsMadeFromFiltersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna que muestra el subtotal para un rango de columnas mediante una fórmula de Excel.
        /// </summary>
        internal static string InfoViewExcelColumnTypeColumnSubTotalTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeColumnSubTotalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna relacionada con una dimensión de tipo concepto.
        /// </summary>
        internal static string InfoViewExcelColumnTypeConceptTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeConceptTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna que muestra los valores de la columna de la dimensión seleccionada.
        /// </summary>
        internal static string InfoViewExcelColumnTypeDimensionTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeDimensionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna que contiene una fórmula de Excel.
        /// </summary>
        internal static string InfoViewExcelColumnTypeExcelFormulaTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeExcelFormulaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna útil para dimensiones tipo Tiempo. Muestra el valor seleccionado y no depende de los filtros creados para esta tabla. Si ya hubiese filtros en esta tabla se agregará una condición OR para contemplar este valor (es decir, &quot;filtros existentes&quot; OR &quot;valor fijo&quot;).
        /// </summary>
        internal static string InfoViewExcelColumnTypeFixedTableValueTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeFixedTableValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna relacionada con una medida DAX.
        /// </summary>
        internal static string InfoViewExcelColumnTypeMeasureTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeMeasureTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna relacionada a una dimensión de tipo tiempo.
        /// </summary>
        internal static string InfoViewExcelColumnTypeTimeTooltip {
            get {
                return ResourceManager.GetString("InfoViewExcelColumnTypeTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Ciclo de aprobación.
        /// </summary>
        internal static string OpenApprovalCycle {
            get {
                return ResourceManager.GetString("OpenApprovalCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Planilla de carga.
        /// </summary>
        internal static string OpenInputForm {
            get {
                return ResourceManager.GetString("OpenInputForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir URL.
        /// </summary>
        internal static string OpenURL {
            get {
                return ResourceManager.GetString("OpenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar correo.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
    }
}
