//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.WebappRoot.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.WebappRoot.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado supera el tamaño permitido de.
        /// </summary>
        internal static string ErrorFileMaxSize {
            get {
                return ResourceManager.GetString("ErrorFileMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo seleccionado no es un tipo permitido.
        /// </summary>
        internal static string ErrorFileTypeNotAllowed {
            get {
                return ResourceManager.GetString("ErrorFileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el tenant indicado..
        /// </summary>
        internal static string ErrorTenantNotFound {
            get {
                return ResourceManager.GetString("ErrorTenantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la base de datos SQL..
        /// </summary>
        internal static string ErrorTenantSQL {
            get {
                return ResourceManager.GetString("ErrorTenantSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la base de datos SSAS..
        /// </summary>
        internal static string ErrorTenantSSAS {
            get {
                return ResourceManager.GetString("ErrorTenantSSAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación ha sido creada..
        /// </summary>
        internal static string InfoApplicationCreated {
            get {
                return ResourceManager.GetString("InfoApplicationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación ha sido borrada..
        /// </summary>
        internal static string InfoApplicationDeleted {
            get {
                return ResourceManager.GetString("InfoApplicationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación ha sido actualizada..
        /// </summary>
        internal static string InfoApplicationUpdated {
            get {
                return ResourceManager.GetString("InfoApplicationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor actual se reemplazará por el valor por defecto..
        /// </summary>
        internal static string InfoDefaultValueWillReplaced {
            get {
                return ResourceManager.GetString("InfoDefaultValueWillReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El endpoint ha sido creado..
        /// </summary>
        internal static string InfoEndpointCreated {
            get {
                return ResourceManager.GetString("InfoEndpointCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El endpoint ha sido borrado..
        /// </summary>
        internal static string InfoEndpointDeleted {
            get {
                return ResourceManager.GetString("InfoEndpointDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoints registrados..
        /// </summary>
        internal static string InfoEndpointRegister {
            get {
                return ResourceManager.GetString("InfoEndpointRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El endpoint ha sido actualizado..
        /// </summary>
        internal static string InfoEndpointUpdated {
            get {
                return ResourceManager.GetString("InfoEndpointUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El menú ha sido creado..
        /// </summary>
        internal static string InfoMenuCreated {
            get {
                return ResourceManager.GetString("InfoMenuCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El menú ha sido borrado..
        /// </summary>
        internal static string InfoMenuDeleted {
            get {
                return ResourceManager.GetString("InfoMenuDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El menú ha sido actualizado..
        /// </summary>
        internal static string InfoMenuUpdated {
            get {
                return ResourceManager.GetString("InfoMenuUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha restaurado el parámetro.
        /// </summary>
        internal static string InfoParametersRestored {
            get {
                return ResourceManager.GetString("InfoParametersRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El permiso ha sido creado..
        /// </summary>
        internal static string InfoPermissionCreated {
            get {
                return ResourceManager.GetString("InfoPermissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El permiso ha sido borrado..
        /// </summary>
        internal static string InfoPermissionDeleted {
            get {
                return ResourceManager.GetString("InfoPermissionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El permiso ha sido actualizado..
        /// </summary>
        internal static string InfoPermissionUpdated {
            get {
                return ResourceManager.GetString("InfoPermissionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol ha sido creado..
        /// </summary>
        internal static string InfoRoleCreated {
            get {
                return ResourceManager.GetString("InfoRoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol ha sido borrado..
        /// </summary>
        internal static string InfoRoleDeleted {
            get {
                return ResourceManager.GetString("InfoRoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol ha sido actualizado..
        /// </summary>
        internal static string InfoRoleUpdated {
            get {
                return ResourceManager.GetString("InfoRoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tenant ha sido creado..
        /// </summary>
        internal static string InfoTenantCreated {
            get {
                return ResourceManager.GetString("InfoTenantCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tenant no posee parámetros para la aplicación seleccionada..
        /// </summary>
        internal static string InfoTenantHaveNotParameters {
            get {
                return ResourceManager.GetString("InfoTenantHaveNotParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuerde buscar para visualizar los parámetros.
        /// </summary>
        internal static string InfoTenantParametersSearchForView {
            get {
                return ResourceManager.GetString("InfoTenantParametersSearchForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tenant ha sido actualizado..
        /// </summary>
        internal static string InfoTenantUpdated {
            get {
                return ResourceManager.GetString("InfoTenantUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de licencia ha sido creado.
        /// </summary>
        internal static string InfoTypeLicenseCreated {
            get {
                return ResourceManager.GetString("InfoTypeLicenseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de licencia ha sido borrado..
        /// </summary>
        internal static string InfoTypeLicenseDeleted {
            get {
                return ResourceManager.GetString("InfoTypeLicenseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de licencia ha sido actualizado..
        /// </summary>
        internal static string InfoTypeLicenseUpdated {
            get {
                return ResourceManager.GetString("InfoTypeLicenseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login a la Derecha, Imagen Fondo a la Izquierda.
        /// </summary>
        internal static string LoginAlingRight {
            get {
                return ResourceManager.GetString("LoginAlingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant creado con éxito..
        /// </summary>
        internal static string SuccessTenantCreate {
            get {
                return ResourceManager.GetString("SuccessTenantCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de datos SQL creada con éxito..
        /// </summary>
        internal static string SuccessTenantSQL {
            get {
                return ResourceManager.GetString("SuccessTenantSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de datos SSAS creada con éxito..
        /// </summary>
        internal static string SuccessTenantSSAS {
            get {
                return ResourceManager.GetString("SuccessTenantSSAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de licencia ya se encuentra seleccionado..
        /// </summary>
        internal static string WarnLicenseTypeIsSelected {
            get {
                return ResourceManager.GetString("WarnLicenseTypeIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un tenant y una aplicación..
        /// </summary>
        internal static string WarnTenantAndApplicationMustSelected {
            get {
                return ResourceManager.GetString("WarnTenantAndApplicationMustSelected", resourceCulture);
            }
        }
    }
}
