//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.Office.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.Office.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de refrescar la hoja? Los cambios se perderán.
        /// </summary>
        internal static string ConfirmRefreshChangesWillLost {
            get {
                return ResourceManager.GetString("ConfirmRefreshChangesWillLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen registros repetidos, ¿Cómo desea continuar?.
        /// </summary>
        internal static string ConfirmRepeatRecordsGroupDiscart {
            get {
                return ResourceManager.GetString("ConfirmRepeatRecordsGroupDiscart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al crear las formulas y los grupos en las filas subtotales.
        /// </summary>
        internal static string ErrorAddSubtotalFormulasAndGroups {
            get {
                return ResourceManager.GetString("ErrorAddSubtotalFormulasAndGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al agregar las filas subtotales.
        /// </summary>
        internal static string ErrorAddSubtotalRows {
            get {
                return ResourceManager.GetString("ErrorAddSubtotalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el paso.
        /// </summary>
        internal static string ErrorBpfStepNotFound {
            get {
                return ResourceManager.GetString("ErrorBpfStepNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al refrescar los datos del formulario.
        /// </summary>
        internal static string ErrorCARefreshingForm {
            get {
                return ResourceManager.GetString("ErrorCARefreshingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un valor mayor a la fecha de comienzo.
        /// </summary>
        internal static string ErrorDateRange {
            get {
                return ResourceManager.GetString("ErrorDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la dimensión tiempo es inválido.
        /// </summary>
        internal static string ErrorDimTimeInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorDimTimeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros en la dimensión tiempo.
        /// </summary>
        internal static string ErrorDimTimeRecordsNotFound {
            get {
                return ResourceManager.GetString("ErrorDimTimeRecordsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al agregar la detección de cambios en la hoja.
        /// </summary>
        internal static string ErrorExcelAddOnChangeSheet {
            get {
                return ResourceManager.GetString("ErrorExcelAddOnChangeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al agregar la detección de cambios en la tabla.
        /// </summary>
        internal static string ErrorExcelAddOnChangeTable {
            get {
                return ResourceManager.GetString("ErrorExcelAddOnChangeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al permitir editar las columnas.
        /// </summary>
        internal static string ErrorExcelColumnEditablePermison {
            get {
                return ResourceManager.GetString("ErrorExcelColumnEditablePermison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear el formato de las columnas.
        /// </summary>
        internal static string ErrorExcelFormatColumnsSetting {
            get {
                return ResourceManager.GetString("ErrorExcelFormatColumnsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear el formato de moneda y subtotales.
        /// </summary>
        internal static string ErrorExcelFormatCurrencyAndSubtotalSetting {
            get {
                return ResourceManager.GetString("ErrorExcelFormatCurrencyAndSubtotalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear el formato numérico en las columnas.
        /// </summary>
        internal static string ErrorExcelFormatNumericColumnsSetting {
            get {
                return ResourceManager.GetString("ErrorExcelFormatNumericColumnsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear las fórmulas de Excel.
        /// </summary>
        internal static string ErrorExcelFormulaSetting {
            get {
                return ResourceManager.GetString("ErrorExcelFormulaSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear los nombres de las columnas padres.
        /// </summary>
        internal static string ErrorExcelHeaderParentNameSet {
            get {
                return ResourceManager.GetString("ErrorExcelHeaderParentNameSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al crear la cabecera de la hoja en Excel.
        /// </summary>
        internal static string ErrorExcelHeaderSheetCreate {
            get {
                return ResourceManager.GetString("ErrorExcelHeaderSheetCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al detectar cambios en la tabla.
        /// </summary>
        internal static string ErrorExcelOnChangeTable {
            get {
                return ResourceManager.GetString("ErrorExcelOnChangeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al guardar el rango donde se realizó el cambio.
        /// </summary>
        internal static string ErrorExcelOnTableChangedStoreRange {
            get {
                return ResourceManager.GetString("ErrorExcelOnTableChangedStoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al pintar y proteger las columnas.
        /// </summary>
        internal static string ErrorExcelPaintAndBlockColumn {
            get {
                return ResourceManager.GetString("ErrorExcelPaintAndBlockColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al pintar y proteger las filas.
        /// </summary>
        internal static string ErrorExcelPaintAndBlockRows {
            get {
                return ResourceManager.GetString("ErrorExcelPaintAndBlockRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error la marcar las filas provenientes del ciclo de aprobación.
        /// </summary>
        internal static string ErrorExcelPaintRowsCA {
            get {
                return ResourceManager.GetString("ErrorExcelPaintRowsCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear el color de las filas de subtotales.
        /// </summary>
        internal static string ErrorExcelRowSubtotalColorSetting {
            get {
                return ResourceManager.GetString("ErrorExcelRowSubtotalColorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al agregar una fila en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetAddRow {
            get {
                return ResourceManager.GetString("ErrorExcelSheetAddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear la visibilidad de las columnas.
        /// </summary>
        internal static string ErrorExcelSheetColumnVisibility {
            get {
                return ResourceManager.GetString("ErrorExcelSheetColumnVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al crear la hoja.
        /// </summary>
        internal static string ErrorExcelSheetCreate {
            get {
                return ResourceManager.GetString("ErrorExcelSheetCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo leer los datos de la hoja de Excel.
        /// </summary>
        internal static string ErrorExcelSheetDataNotRecovered {
            get {
                return ResourceManager.GetString("ErrorExcelSheetDataNotRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al obtener los datos de la hoja.
        /// </summary>
        internal static string ErrorExcelSheetGetData {
            get {
                return ResourceManager.GetString("ErrorExcelSheetGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al agrupar las filas en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetGroupsRows {
            get {
                return ResourceManager.GetString("ErrorExcelSheetGroupsRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear los valores iniciales en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetInitialValueSetting {
            get {
                return ResourceManager.GetString("ErrorExcelSheetInitialValueSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al pegar los datos en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetPasteData {
            get {
                return ResourceManager.GetString("ErrorExcelSheetPasteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al quitar una fila en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetRemoveRow {
            get {
                return ResourceManager.GetString("ErrorExcelSheetRemoveRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear las listas de validación tipo checkbox en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetValidationListCheckboxSetting {
            get {
                return ResourceManager.GetString("ErrorExcelSheetValidationListCheckboxSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear las listas de validación en la hoja.
        /// </summary>
        internal static string ErrorExcelSheetValidationListSetting {
            get {
                return ResourceManager.GetString("ErrorExcelSheetValidationListSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al setear los colores de la tabla.
        /// </summary>
        internal static string ErrorExcelTableColorSetting {
            get {
                return ResourceManager.GetString("ErrorExcelTableColorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay un problema con el formulario, tiene filtros internos/ocultos seteados incorrectamente..
        /// </summary>
        internal static string ErrorHiddenFilters {
            get {
                return ResourceManager.GetString("ErrorHiddenFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La granularidad de la dimensión tiempo no está definida.
        /// </summary>
        internal static string ErrorModelTimeGranularityNotDefined {
            get {
                return ResourceManager.GetString("ErrorModelTimeGranularityNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al pivotar los datos.
        /// </summary>
        internal static string ErrorPivotingData {
            get {
                return ResourceManager.GetString("ErrorPivotingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al despivotar los datos.
        /// </summary>
        internal static string ErrorUnpivotingData {
            get {
                return ResourceManager.GetString("ErrorUnpivotingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron ciclos de aprobación.
        /// </summary>
        internal static string InfoApprovalCyclesNotFound {
            get {
                return ResourceManager.GetString("InfoApprovalCyclesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron flujos de proceso de negocio.
        /// </summary>
        internal static string InfoBPFUserNotFound {
            get {
                return ResourceManager.GetString("InfoBPFUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos.
        /// </summary>
        internal static string InfoDataNotFound {
            get {
                return ResourceManager.GetString("InfoDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser administrador para ejecutar la regla de datos.
        /// </summary>
        internal static string InfoDataRuleExecAdmin {
            get {
                return ResourceManager.GetString("InfoDataRuleExecAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La regla de datos fue ejecutada con éxito.
        /// </summary>
        internal static string InfoDataRuleProfileExecuted {
            get {
                return ResourceManager.GetString("InfoDataRuleProfileExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interactue con la hoja de Excel hasta que haya terminado el proceso.
        /// </summary>
        internal static string InfoExcelDontInteractWithSheet {
            get {
                return ResourceManager.GetString("InfoExcelDontInteractWithSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Planilla de carga de datos.
        /// </summary>
        internal static string InfoInputFormsNotFound {
            get {
                return ResourceManager.GetString("InfoInputFormsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo no tiene asignada una granularidad para la dimensión tiempo.
        /// </summary>
        internal static string InfoModelGranularityNotAssigned {
            get {
                return ResourceManager.GetString("InfoModelGranularityNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay dimensiones para bloquear.
        /// </summary>
        internal static string InfoNoDimensionsToBlock {
            get {
                return ResourceManager.GetString("InfoNoDimensionsToBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay dimensiones o nodos para bloquear.
        /// </summary>
        internal static string InfoNoDimensionsToBlockOrNodes {
            get {
                return ResourceManager.GetString("InfoNoDimensionsToBlockOrNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron tablas del tipo indicado.
        /// </summary>
        internal static string InfoTableTypeNotFound {
            get {
                return ResourceManager.GetString("InfoTableTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hoja activa es de solo lectura. La hoja de trabajo es \&apos;{0}\&apos;.
        /// </summary>
        internal static string WarnExcelActiveSheet {
            get {
                return ResourceManager.GetString("WarnExcelActiveSheet", resourceCulture);
            }
        }
    }
}
