// <auto-generated />
using System;
using AcgFotos.Base.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcgFotos.Base.SqlMigrations.Migrations
{
    [DbContext(typeof(AcgFotosDbContext))]
    partial class AcgFotosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Aplicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gen_Aplicaciones", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientUserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Duracion")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("ImpersonatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Metodo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parametros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestAbsolutePath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ResultContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultStatusCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Servicio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("ix_auditlog_fechahora");

                    b.HasIndex("UsuarioId");

                    b.ToTable("gen_AuditLogs", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.AuthzVersion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("gen_AuthzVersion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Version = 0L
                        });
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Endpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Namespace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Route", "HttpMethod")
                        .IsUnique()
                        .HasDatabaseName("uk_endpoint_route_method")
                        .HasFilter("[Route] IS NOT NULL AND [HttpMethod] IS NOT NULL");

                    b.ToTable("gen_EndPoints", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Grupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_grupo_tenant");

                    b.ToTable("gen_Grupos", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.GrupoRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("RolId");

                    b.HasIndex("TenantId", "GrupoId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("uk_tenant_grupo_rol");

                    b.ToTable("gen_GrupoRoles", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.LogInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("gen_LogInfos", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenWeb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MenuPadreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long?>("PermisoId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoutePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisibleDash")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibleSideMenu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_menu_codigo");

                    b.HasIndex("MenuPadreId");

                    b.HasIndex("PermisoId");

                    b.ToTable("gen_Menus", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Parametro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("PermisoId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDato")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("PermisoId");

                    b.ToTable("gen_Parametros", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.ParametroValorTenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ParametroId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParametroId");

                    b.HasIndex("TenantId", "ParametroId")
                        .IsUnique();

                    b.ToTable("gen_ParametrosValoresTenants", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Permiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoPermiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsRestringido")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("PermisoPadreId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("PermisoPadreId");

                    b.ToTable("gen_Permisos", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.PermisoEndpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EndpointId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermisoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("PermisoId", "EndpointId")
                        .IsUnique()
                        .HasDatabaseName("uk_permisos_endpoints");

                    b.ToTable("gen_PermisoEndpoints", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CreatedByUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("gen_RefreshTokens", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsDefaultParaNuevoTenant")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("gen_Roles", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PermisoId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.ToTable("gen_RolPermisos", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ColorPrimarioDark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorPrimarioLight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DarkModeByDefault")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenFondoLoginDarkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenFondoLoginLightUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoHeaderDarkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoHeaderLightUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoLoginDarkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoLoginLightUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StyleSheetCssUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoLayoutLogin")
                        .HasColumnType("int");

                    b.Property<string>("TituloWeb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("gen_Tenants", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TenantAplicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("TenantId");

                    b.ToTable("gen_TenantAplicaciones", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TenantFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("gen_TenantFiles", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TenantLicencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("datetime2");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoLicenciaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TipoLicenciaId");

                    b.ToTable("gen_TenantLicencias", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TipoLicencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoTipoLicencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsDefaultParaNuevoTenant")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("gen_TipoLicencia", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TipoLicenciaRoles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoLicenciaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("TipoLicenciaId");

                    b.ToTable("gen_TipoLicenciaRoles", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCambioClave")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TokenExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("gen_Usuarios", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioAplicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AplicacionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Default")
                        .HasColumnType("bit");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("gen_UsuarioAplicaciones", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioGrupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GrupoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_usuariogrupo_usuario");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UsuarioId"), new[] { "GrupoId", "TenantId" });

                    b.HasIndex("TenantId", "GrupoId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uk_tenant_grupo_usuario");

                    b.ToTable("gen_UsuarioGrupos", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioHistorial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Periodo")
                        .HasDatabaseName("IX_gen_UsuariosHistorial_TenantId_Periodo");

                    b.ToTable("gen_UsuariosHistorial", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("uk_usuario_rol");

                    b.ToTable("gen_UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioRolEfectivo", b =>
                {
                    b.Property<long?>("GrupoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Origen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermitidoPorLicencia")
                        .HasColumnType("bit");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_UsuarioRolesEfectivos", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioTipoLicencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoLicenciaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TipoLicenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("gen_UsuarioTipoLicencia", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuariosActivosMensual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("gen_UsuariosActivosMensuales", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.GrupoRol", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Grupo", "Grupo")
                        .WithMany("GrupoRoles")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Menu", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Aplicacion", "Aplicacion")
                        .WithMany()
                        .HasForeignKey("AplicacionId");

                    b.HasOne("AcgFotos.Base.Domain.Entities.Menu", "MenuPadre")
                        .WithMany("MenuHijos")
                        .HasForeignKey("MenuPadreId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("AcgFotos.Base.Domain.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId");

                    b.Navigation("Aplicacion");

                    b.Navigation("MenuPadre");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Parametro", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Aplicacion", "Aplicacion")
                        .WithMany()
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aplicacion");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.ParametroValorTenant", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Parametro", "Parametro")
                        .WithMany()
                        .HasForeignKey("ParametroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parametro");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Permiso", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Aplicacion", "Aplicacion")
                        .WithMany()
                        .HasForeignKey("AplicacionId");

                    b.HasOne("AcgFotos.Base.Domain.Entities.Permiso", "PermisoPadre")
                        .WithMany("PermisosHijos")
                        .HasForeignKey("PermisoPadreId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Aplicacion");

                    b.Navigation("PermisoPadre");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.PermisoEndpoint", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Endpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Permiso", null)
                        .WithMany("Endpoints")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TenantAplicacion", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Aplicacion", "Aplicacion")
                        .WithMany("TenantAplicaciones")
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantAplicaciones")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacion");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TenantFile", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TenantLicencia", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantLicenses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.TipoLicencia", "TipoLicencia")
                        .WithMany("TenantLicenses")
                        .HasForeignKey("TipoLicenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("TipoLicencia");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TipoLicenciaRoles", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Rol", "Rol")
                        .WithMany("TipoLicenciaRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.TipoLicencia", "TipoLicencia")
                        .WithMany("TipoLicenciaRoles")
                        .HasForeignKey("TipoLicenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoLicencia");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioAplicacion", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Aplicacion", "Aplicacion")
                        .WithMany("UsuarioAplicaciones")
                        .HasForeignKey("AplicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioAplicaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioGrupo", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Grupo", "Grupo")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.UsuarioTipoLicencia", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.TipoLicencia", "TipoLicencia")
                        .WithMany("UsuarioTipoLicencia")
                        .HasForeignKey("TipoLicenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoLicencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("AcgFotos.Base.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Aplicacion", b =>
                {
                    b.Navigation("TenantAplicaciones");

                    b.Navigation("UsuarioAplicaciones");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("GrupoRoles");

                    b.Navigation("UsuarioGrupos");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Menu", b =>
                {
                    b.Navigation("MenuHijos");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("Endpoints");

                    b.Navigation("PermisosHijos");

                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("TipoLicenciaRoles");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("TenantAplicaciones");

                    b.Navigation("TenantLicenses");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.TipoLicencia", b =>
                {
                    b.Navigation("TenantLicenses");

                    b.Navigation("TipoLicenciaRoles");

                    b.Navigation("UsuarioTipoLicencia");
                });

            modelBuilder.Entity("AcgFotos.Base.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("UsuarioAplicaciones");

                    b.Navigation("UsuarioGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
