//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.Webapp.Fields {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.Webapp.Fields.Fields", typeof(Fields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario/a.
        /// </summary>
        internal static string Addressee {
            get {
                return ResourceManager.GetString("Addressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar dimensión.
        /// </summary>
        internal static string AdminDimension {
            get {
                return ResourceManager.GetString("AdminDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar modelo.
        /// </summary>
        internal static string AdminModel {
            get {
                return ResourceManager.GetString("AdminModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Tenant.
        /// </summary>
        internal static string AdminTenantClient {
            get {
                return ResourceManager.GetString("AdminTenantClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Función de agregación.
        /// </summary>
        internal static string AggregateFunction {
            get {
                return ResourceManager.GetString("AggregateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir editar.
        /// </summary>
        internal static string AllowEdit {
            get {
                return ResourceManager.GetString("AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar filtro.
        /// </summary>
        internal static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la aplicación.
        /// </summary>
        internal static string AppSelector {
            get {
                return ResourceManager.GetString("AppSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguís ahí?.
        /// </summary>
        internal static string AreYouThere {
            get {
                return ResourceManager.GetString("AreYouThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar.
        /// </summary>
        internal static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignadas.
        /// </summary>
        internal static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos disponibles.
        /// </summary>
        internal static string AvaiableFields {
            get {
                return ResourceManager.GetString("AvaiableFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibles.
        /// </summary>
        internal static string Availables {
            get {
                return ResourceManager.GetString("Availables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color de fondo.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genera archivo en base a los colores selccionados.
        /// </summary>
        internal static string BuildFileBasedOnColors {
            get {
                return ResourceManager.GetString("BuildFileBasedOnColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede editar los datos de los hijos.
        /// </summary>
        internal static string CanEditChildrenData {
            get {
                return ResourceManager.GetString("CanEditChildrenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrado.
        /// </summary>
        internal static string Centered {
            get {
                return ResourceManager.GetString("Centered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar aplicación.
        /// </summary>
        internal static string ChangeApp {
            get {
                return ResourceManager.GetString("ChangeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columna.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de columna.
        /// </summary>
        internal static string ColumnConfiguration {
            get {
                return ResourceManager.GetString("ColumnConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre columna.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de la columna.
        /// </summary>
        internal static string ColumnOrder {
            get {
                return ResourceManager.GetString("ColumnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de columna que muestra el valor seleccionado y depende de los filtros creados para esta tabla.
        /// </summary>
        internal static string ColumnPivotType {
            get {
                return ResourceManager.GetString("ColumnPivotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnas.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnas creadas a partir de los filtros.
        /// </summary>
        internal static string ColumnsMadeFromFilters {
            get {
                return ResourceManager.GetString("ColumnsMadeFromFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columna subtotal.
        /// </summary>
        internal static string ColumnSubTotal {
            get {
                return ResourceManager.GetString("ColumnSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columna numérica del modelo.
        /// </summary>
        internal static string ColumnValue {
            get {
                return ResourceManager.GetString("ColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure el estilo general .
        /// </summary>
        internal static string ConfigParamsGral {
            get {
                return ResourceManager.GetString("ConfigParamsGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure el estilo para Office.
        /// </summary>
        internal static string ConfigParamsOffice {
            get {
                return ResourceManager.GetString("ConfigParamsOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure el estilo para la webapp.
        /// </summary>
        internal static string ConfigParamsWebapp {
            get {
                return ResourceManager.GetString("ConfigParamsWebapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros de contexto.
        /// </summary>
        internal static string ContextParams {
            get {
                return ResourceManager.GetString("ContextParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiado entre modelos.
        /// </summary>
        internal static string CopyBetweenModels {
            get {
                return ResourceManager.GetString("CopyBetweenModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant. Filas leidas del origen.
        /// </summary>
        internal static string CountRowsSourceReaded {
            get {
                return ResourceManager.GetString("CountRowsSourceReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expresión cron.
        /// </summary>
        internal static string CronExpression {
            get {
                return ResourceManager.GetString("CronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizado.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar fórmula.
        /// </summary>
        internal static string CustomizeFormula {
            get {
                return ResourceManager.GetString("CustomizeFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar columnas.
        /// </summary>
        internal static string CustumizeColumns {
            get {
                return ResourceManager.GetString("CustumizeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema oscuro por defecto.
        /// </summary>
        internal static string DarkModeDefault {
            get {
                return ResourceManager.GetString("DarkModeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema Oscuro.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la regla de datos.
        /// </summary>
        internal static string DataRuleName {
            get {
                return ResourceManager.GetString("DataRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de fuente de datos.
        /// </summary>
        internal static string DatasourceType {
            get {
                return ResourceManager.GetString("DatasourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de dato.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora.
        /// </summary>
        internal static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de fin.
        /// </summary>
        internal static string DateTimeEnd {
            get {
                return ResourceManager.GetString("DateTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio.
        /// </summary>
        internal static string DateTimeStart {
            get {
                return ResourceManager.GetString("DateTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expresión DAX.
        /// </summary>
        internal static string DAXExpression {
            get {
                return ResourceManager.GetString("DAXExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Función Dax.
        /// </summary>
        internal static string DaxFunction {
            get {
                return ResourceManager.GetString("DaxFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaración Dax.
        /// </summary>
        internal static string DaxStatement {
            get {
                return ResourceManager.GetString("DaxStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación por defecto.
        /// </summary>
        internal static string DefaultAppication {
            get {
                return ResourceManager.GetString("DefaultAppication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerarquía por defecto.
        /// </summary>
        internal static string DefaultHierarchy {
            get {
                return ResourceManager.GetString("DefaultHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor por defecto.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar jerarquía.
        /// </summary>
        internal static string DeleteHierarchy {
            get {
                return ResourceManager.GetString("DeleteHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar estructura.
        /// </summary>
        internal static string DeleteStructure {
            get {
                return ResourceManager.GetString("DeleteStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensión clásica.
        /// </summary>
        internal static string DimensionClassic {
            get {
                return ResourceManager.GetString("DimensionClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columna de la dimensión.
        /// </summary>
        internal static string DimensionColumn {
            get {
                return ResourceManager.GetString("DimensionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos de dimensión.
        /// </summary>
        internal static string DimensionFields {
            get {
                return ResourceManager.GetString("DimensionFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre dimensión.
        /// </summary>
        internal static string DimensionName {
            get {
                return ResourceManager.GetString("DimensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensión padre-hijo.
        /// </summary>
        internal static string DimensionParentChild {
            get {
                return ResourceManager.GetString("DimensionParentChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensiones disponibles.
        /// </summary>
        internal static string DimensionsAvailable {
            get {
                return ResourceManager.GetString("DimensionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensión a bloquear.
        /// </summary>
        internal static string DimensionsBlocked {
            get {
                return ResourceManager.GetString("DimensionsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensión relacionada.
        /// </summary>
        internal static string DimensionsRelated {
            get {
                return ResourceManager.GetString("DimensionsRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo dimensión.
        /// </summary>
        internal static string DimensionType {
            get {
                return ResourceManager.GetString("DimensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de la dimensión.
        /// </summary>
        internal static string DimensionValue {
            get {
                return ResourceManager.GetString("DimensionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar como fila subtotal.
        /// </summary>
        internal static string DisabledAsSubtotal {
            get {
                return ResourceManager.GetString("DisabledAsSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar columna de Excel.
        /// </summary>
        internal static string DisabledExcelColumn {
            get {
                return ResourceManager.GetString("DisabledExcelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro deshabilitado.
        /// </summary>
        internal static string DisabledExcelFilter {
            get {
                return ResourceManager.GetString("DisabledExcelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disolviendo cambios....
        /// </summary>
        internal static string DissolvingChanges {
            get {
                return ResourceManager.GetString("DissolvingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar {0}.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar {0}.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones de correos.
        /// </summary>
        internal static string EmailAddresses {
            get {
                return ResourceManager.GetString("EmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a enviar correo de confirmación.
        /// </summary>
        internal static string EmailReConfirm {
            get {
                return ResourceManager.GetString("EmailReConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay columnas agregadas.
        /// </summary>
        internal static string EmptyExcelColumns {
            get {
                return ResourceManager.GetString("EmptyExcelColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar como fila subtotal.
        /// </summary>
        internal static string EnabledAsSubtotal {
            get {
                return ResourceManager.GetString("EnabledAsSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar columna de Excel.
        /// </summary>
        internal static string EnabledExcelColumn {
            get {
                return ResourceManager.GetString("EnabledExcelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro habilitado.
        /// </summary>
        internal static string EnabledExcelFilter {
            get {
                return ResourceManager.GetString("EnabledExcelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un valor de busqueda.
        /// </summary>
        internal static string EnterValueToSearch {
            get {
                return ResourceManager.GetString("EnterValueToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplos de fórmulas.
        /// </summary>
        internal static string ExampleOfFormula {
            get {
                return ResourceManager.GetString("ExampleOfFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizando los nombres de cabecera. Para una Planilla de carga de 2 niveles sería:.
        /// </summary>
        internal static string ExampleRefColByHeaders {
            get {
                return ResourceManager.GetString("ExampleRefColByHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizando la letra de la columna: A.
        /// </summary>
        internal static string ExampleRefColByLetter {
            get {
                return ResourceManager.GetString("ExampleRefColByLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenciar una columna en Excel.
        /// </summary>
        internal static string ExampleRefColExcel {
            get {
                return ResourceManager.GetString("ExampleRefColExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columna de Excel.
        /// </summary>
        internal static string ExcelColumn {
            get {
                return ResourceManager.GetString("ExcelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna ya existe.
        /// </summary>
        internal static string ExcelColumnExists {
            get {
                return ResourceManager.GetString("ExcelColumnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete los campos requeridos.
        /// </summary>
        internal static string ExcelColumnsRequired {
            get {
                return ResourceManager.GetString("ExcelColumnsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula de Excel.
        /// </summary>
        internal static string ExcelFormula {
            get {
                return ResourceManager.GetString("ExcelFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo fórmula de Excel.
        /// </summary>
        internal static string ExcelFormulaType {
            get {
                return ResourceManager.GetString("ExcelFormulaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la hoja de Excel.
        /// </summary>
        internal static string ExcelSheetName {
            get {
                return ResourceManager.GetString("ExcelSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutado desde.
        /// </summary>
        internal static string ExecutedFrom {
            get {
                return ResourceManager.GetString("ExecutedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar consulta.
        /// </summary>
        internal static string ExecuteQuery {
            get {
                return ResourceManager.GetString("ExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar datos.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expresión.
        /// </summary>
        internal static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por este estado.
        /// </summary>
        internal static string FilterByStatus {
            get {
                return ResourceManager.GetString("FilterByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar filtro de estado.
        /// </summary>
        internal static string FilterByStatusRemove {
            get {
                return ResourceManager.GetString("FilterByStatusRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columna a filtrar.
        /// </summary>
        internal static string FilterColumn {
            get {
                return ResourceManager.GetString("FilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición a filtrar.
        /// </summary>
        internal static string FilterColumnCondition {
            get {
                return ResourceManager.GetString("FilterColumnCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar filtro.
        /// </summary>
        internal static string FilterConfiguration {
            get {
                return ResourceManager.GetString("FilterConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar estructura.
        /// </summary>
        internal static string FilterStructures {
            get {
                return ResourceManager.GetString("FilterStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtar valores de la tabla.
        /// </summary>
        internal static string FilterTableValues {
            get {
                return ResourceManager.GetString("FilterTableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer nodo.
        /// </summary>
        internal static string FirstNode {
            get {
                return ResourceManager.GetString("FirstNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor fijo de la tabla.
        /// </summary>
        internal static string FixedTableValue {
            get {
                return ResourceManager.GetString("FixedTableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color de fuente.
        /// </summary>
        internal static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inmovilizar columna.
        /// </summary>
        internal static string FreezeColumn {
            get {
                return ResourceManager.GetString("FreezeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos generales.
        /// </summary>
        internal static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de cabecera.
        /// </summary>
        internal static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar {0}.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerarquías.
        /// </summary>
        internal static string Hierarchies {
            get {
                return ResourceManager.GetString("Hierarchies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerarquía.
        /// </summary>
        internal static string Hierarchy {
            get {
                return ResourceManager.GetString("Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerarquía dimensión tiempo.
        /// </summary>
        internal static string HierarchyTime {
            get {
                return ResourceManager.GetString("HierarchyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar datos.
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir registros sin valores en el modelo.
        /// </summary>
        internal static string IncludeRecordsWithoutModelValues {
            get {
                return ResourceManager.GetString("IncludeRecordsWithoutModelValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        internal static string Indicadores {
            get {
                return ResourceManager.GetString("Indicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de entrada.
        /// </summary>
        internal static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es manejado por el proceso.
        /// </summary>
        internal static string isDrivenByProcess {
            get {
                return ResourceManager.GetString("isDrivenByProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es oculto.
        /// </summary>
        internal static string IsHidden {
            get {
                return ResourceManager.GetString("IsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es visible.
        /// </summary>
        internal static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representa al número de la fila y será reemplazado al aplicarlo en Excel.
        /// </summary>
        internal static string KeyWord_hastag {
            get {
                return ResourceManager.GetString("KeyWord_hastag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representa al campo rango y será reemplazado al aplicarlo en Excel.
        /// </summary>
        internal static string KeyWord_range {
            get {
                return ResourceManager.GetString("KeyWord_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabras clave.
        /// </summary>
        internal static string KeyWords {
            get {
                return ResourceManager.GetString("KeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última ejecución.
        /// </summary>
        internal static string LastExecution {
            get {
                return ResourceManager.GetString("LastExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último ingreso.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último estado.
        /// </summary>
        internal static string LastStatus {
            get {
                return ResourceManager.GetString("LastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar nivel.
        /// </summary>
        internal static string LevelConfiguration {
            get {
                return ResourceManager.GetString("LevelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveles.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencias disponibles.
        /// </summary>
        internal static string LicensesAvailable {
            get {
                return ResourceManager.GetString("LicensesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema claro por defecto.
        /// </summary>
        internal static string LightModeDefault {
            get {
                return ResourceManager.GetString("LightModeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema Claro.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear usuario.
        /// </summary>
        internal static string LockUser {
            get {
                return ResourceManager.GetString("LockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login a la Izquierda, Imagen Fondo a la Derecha.
        /// </summary>
        internal static string LoginAlignLeft {
            get {
                return ResourceManager.GetString("LoginAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login a la Derecha, Imagen Fondo a la Izquierda.
        /// </summary>
        internal static string LoginAlignRight {
            get {
                return ResourceManager.GetString("LoginAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen de Fondo login.
        /// </summary>
        internal static string LoginImageBackground {
            get {
                return ResourceManager.GetString("LoginImageBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Logo Login.
        /// </summary>
        internal static string LoginImageLogo {
            get {
                return ResourceManager.GetString("LoginImageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Logo Cabecera.
        /// </summary>
        internal static string LogoImageHeader {
            get {
                return ResourceManager.GetString("LogoImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar estados.
        /// </summary>
        internal static string ManageStatus {
            get {
                return ResourceManager.GetString("ManageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecución manual.
        /// </summary>
        internal static string ManualTrigger {
            get {
                return ResourceManager.GetString("ManualTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeo de columnas.
        /// </summary>
        internal static string MapColumns {
            get {
                return ResourceManager.GetString("MapColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medida.
        /// </summary>
        internal static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medidas.
        /// </summary>
        internal static string Measures {
            get {
                return ResourceManager.GetString("Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo medida.
        /// </summary>
        internal static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo relacionado.
        /// </summary>
        internal static string ModelRelated {
            get {
                return ResourceManager.GetString("ModelRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se necesita asignar  la granularidad del modelo.
        /// </summary>
        internal static string ModelTimeGranularityNeeded {
            get {
                return ResourceManager.GetString("ModelTimeGranularityNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de modo.
        /// </summary>
        internal static string ModeType {
            get {
                return ResourceManager.GetString("ModeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un: &apos;{0}&apos;.
        /// </summary>
        internal static string MustEnterA {
            get {
                return ResourceManager.GetString("MustEnterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la programación.
        /// </summary>
        internal static string NameSchedule {
            get {
                return ResourceManager.GetString("NameSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima ejecución.
        /// </summary>
        internal static string NextExec {
            get {
                return ResourceManager.GetString("NextExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin parámetros de contexto.
        /// </summary>
        internal static string NoContextParams {
            get {
                return ResourceManager.GetString("NoContextParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo.
        /// </summary>
        internal static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo relacionado.
        /// </summary>
        internal static string NodeRelated {
            get {
                return ResourceManager.GetString("NodeRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron resultados.
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje de notificación.
        /// </summary>
        internal static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        internal static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se permiten archivos {0}.
        /// </summary>
        internal static string OnlyAllowedFilesType {
            get {
                return ResourceManager.GetString("OnlyAllowedFilesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnas padre-hijo originales.
        /// </summary>
        internal static string OriginalsColumnsParentChild {
            get {
                return ResourceManager.GetString("OriginalsColumnsParentChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactualizado.
        /// </summary>
        internal static string Outdated {
            get {
                return ResourceManager.GetString("Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padre.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padre-hijo.
        /// </summary>
        internal static string ParentChild {
            get {
                return ResourceManager.GetString("ParentChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo padre.
        /// </summary>
        internal static string ParentNode {
            get {
                return ResourceManager.GetString("ParentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista previa.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña anterior.
        /// </summary>
        internal static string PreviousPassword {
            get {
                return ResourceManager.GetString("PreviousPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color primario.
        /// </summary>
        internal static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidad.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contexto de proceso.
        /// </summary>
        internal static string ProcessContext {
            get {
                return ResourceManager.GetString("ProcessContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flujo del proceso.
        /// </summary>
        internal static string ProcessFlow {
            get {
                return ResourceManager.GetString("ProcessFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil activo.
        /// </summary>
        internal static string ProfileActive {
            get {
                return ResourceManager.GetString("ProfileActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta DAX.
        /// </summary>
        internal static string QueryDax {
            get {
                return ResourceManager.GetString("QueryDax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda para la consulta DAX.
        /// </summary>
        internal static string QueryDaxHelp {
            get {
                return ResourceManager.GetString("QueryDaxHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta DAX unpivot.
        /// </summary>
        internal static string QueryDaxUnpivot {
            get {
                return ResourceManager.GetString("QueryDaxUnpivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto - Real.
        /// </summary>
        internal static string RealsConcept {
            get {
                return ResourceManager.GetString("RealsConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo - Real.
        /// </summary>
        internal static string RealsTime {
            get {
                return ResourceManager.GetString("RealsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo real.
        /// </summary>
        internal static string RealType {
            get {
                return ResourceManager.GetString("RealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaciones.
        /// </summary>
        internal static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintentar.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolver valores.
        /// </summary>
        internal static string ReturnValues {
            get {
                return ResourceManager.GetString("ReturnValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fila.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filas.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de la fila subtotal.
        /// </summary>
        internal static string RowsSubtotalOrder {
            get {
                return ResourceManager.GetString("RowsSubtotalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de ejecuciones.
        /// </summary>
        internal static string RunsHistory {
            get {
                return ResourceManager.GetString("RunsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segura.
        /// </summary>
        internal static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y diseñar consultas.
        /// </summary>
        internal static string SaveAndDesignQueries {
            get {
                return ResourceManager.GetString("SaveAndDesignQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar nodo.
        /// </summary>
        internal static string SaveNode {
            get {
                return ResourceManager.GetString("SaveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método a programar.
        /// </summary>
        internal static string SchedulableMethod {
            get {
                return ResourceManager.GetString("SchedulableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programar.
        /// </summary>
        internal static string Schedulate {
            get {
                return ResourceManager.GetString("Schedulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecucción programada.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando resultados.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un valor de busqueda..
        /// </summary>
        internal static string SearchValue {
            get {
                return ResourceManager.GetString("SearchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color secundario.
        /// </summary>
        internal static string SecondaryColor {
            get {
                return ResourceManager.GetString("SecondaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo valor a filtar.
        /// </summary>
        internal static string SecondValueToFilter {
            get {
                return ResourceManager.GetString("SecondValueToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguro.
        /// </summary>
        internal static string Secure {
            get {
                return ResourceManager.GetString("Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector Cliente / Usuario.
        /// </summary>
        internal static string SelectClientUser {
            get {
                return ResourceManager.GetString("SelectClientUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar columnas.
        /// </summary>
        internal static string SelectColumns {
            get {
                return ResourceManager.GetString("SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una imagen para poder visualizarla.
        /// </summary>
        internal static string SelectImageToPreview {
            get {
                return ResourceManager.GetString("SelectImageToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valor de la tabla.
        /// </summary>
        internal static string SelectTableValue {
            get {
                return ResourceManager.GetString("SelectTableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valor.
        /// </summary>
        internal static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitente.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar notificación.
        /// </summary>
        internal static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar al padre.
        /// </summary>
        internal static string SendToParent {
            get {
                return ResourceManager.GetString("SendToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabecera de la hoja.
        /// </summary>
        internal static string SheetHeader {
            get {
                return ResourceManager.GetString("SheetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar todo.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar todo el historial de ejecución.
        /// </summary>
        internal static string ShowAllRunsHistory {
            get {
                return ResourceManager.GetString("ShowAllRunsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar medidas clásicas.
        /// </summary>
        internal static string ShowClassicMeasures {
            get {
                return ResourceManager.GetString("ShowClassicMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar los items seleccionados.
        /// </summary>
        internal static string ShowSelectedItems {
            get {
                return ResourceManager.GetString("ShowSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijo.
        /// </summary>
        internal static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla origen.
        /// </summary>
        internal static string SourceTable {
            get {
                return ResourceManager.GetString("SourceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separar columnas reales.
        /// </summary>
        internal static string SplitRealsColumns {
            get {
                return ResourceManager.GetString("SplitRealsColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha comienzo.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguir conectado.
        /// </summary>
        internal static string StayConnected {
            get {
                return ResourceManager.GetString("StayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura.
        /// </summary>
        internal static string Structure {
            get {
                return ResourceManager.GetString("Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoja de estilo.
        /// </summary>
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subpaso.
        /// </summary>
        internal static string SubStep {
            get {
                return ResourceManager.GetString("SubStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula subtotal.
        /// </summary>
        internal static string SubtotalFormula {
            get {
                return ResourceManager.GetString("SubtotalFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintaxis.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabecera de la tabla.
        /// </summary>
        internal static string TableHeader {
            get {
                return ResourceManager.GetString("TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadatos correctos.
        /// </summary>
        internal static string TableSynchronized {
            get {
                return ResourceManager.GetString("TableSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores de la tabla.
        /// </summary>
        internal static string TableValues {
            get {
                return ResourceManager.GetString("TableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar del filtro.
        /// </summary>
        internal static string TakeFromFilter {
            get {
                return ResourceManager.GetString("TakeFromFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo destino.
        /// </summary>
        internal static string TargetNode {
            get {
                return ResourceManager.GetString("TargetNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla destino.
        /// </summary>
        internal static string TargetTable {
            get {
                return ResourceManager.GetString("TargetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción de tarea.
        /// </summary>
        internal static string TaskAction {
            get {
                return ResourceManager.GetString("TaskAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la tarea.
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y Condiciones.
        /// </summary>
        internal static string TermAndConditions {
            get {
                return ResourceManager.GetString("TermAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La medida tiene un concepto relacionado.
        /// </summary>
        internal static string TheMeasureHasAConceptRelated {
            get {
                return ResourceManager.GetString("TheMeasureHasAConceptRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granularidad para la dimensión tiempo.
        /// </summary>
        internal static string TimeGranularity {
            get {
                return ResourceManager.GetString("TimeGranularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear usuario.
        /// </summary>
        internal static string UnlockUser {
            get {
                return ResourceManager.GetString("UnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo sin verificar.
        /// </summary>
        internal static string UnverifiedEmail {
            get {
                return ResourceManager.GetString("UnverifiedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar el valor del contexto global.
        /// </summary>
        internal static string UseContextGlobalValue {
            get {
                return ResourceManager.GetString("UseContextGlobalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor a filtrar.
        /// </summary>
        internal static string ValueToFilter {
            get {
                return ResourceManager.GetString("ValueToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo verificado.
        /// </summary>
        internal static string VerifiedEmail {
            get {
                return ResourceManager.GetString("VerifiedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la Vista.
        /// </summary>
        internal static string ViewName {
            get {
                return ResourceManager.GetString("ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar {0}.
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros visuales.
        /// </summary>
        internal static string VisualFilters {
            get {
                return ResourceManager.GetString("VisualFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
