//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.Office.Fields {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.Office.Fields.Fields", typeof(Fields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flujos de procesos de negocio.
        /// </summary>
        internal static string BusinessProcessFlows {
            get {
                return ResourceManager.GetString("BusinessProcessFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiando la visibilidad de las columnas.
        /// </summary>
        internal static string ChangingVisibleColumns {
            get {
                return ResourceManager.GetString("ChangingVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contexto.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando cabecera.
        /// </summary>
        internal static string CreatingHeader {
            get {
                return ResourceManager.GetString("CreatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos por default.
        /// </summary>
        internal static string DefaultPermissions {
            get {
                return ResourceManager.GetString("DefaultPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descartar.
        /// </summary>
        internal static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando datos.
        /// </summary>
        internal static string DownloadingData {
            get {
                return ResourceManager.GetString("DownloadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar regla de datos.
        /// </summary>
        internal static string ExecuteDataRule {
            get {
                return ResourceManager.GetString("ExecuteDataRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han modificado los siguientes set de datos.
        /// </summary>
        internal static string FollowingDataSetHaveBeenModified {
            get {
                return ResourceManager.GetString("FollowingDataSetHaveBeenModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una opción tipo real.
        /// </summary>
        internal static string MustHaveARealOption {
            get {
                return ResourceManager.GetString("MustHaveARealOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva jerarquia.
        /// </summary>
        internal static string NewHierarchy {
            get {
                return ResourceManager.GetString("NewHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodos a notificar.
        /// </summary>
        internal static string NotificationNode {
            get {
                return ResourceManager.GetString("NotificationNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han notificado a.
        /// </summary>
        internal static string NotificationSentNode {
            get {
                return ResourceManager.GetString("NotificationSentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pintado columnas editables.
        /// </summary>
        internal static string PaintingEditableColumns {
            get {
                return ResourceManager.GetString("PaintingEditableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegando datos.
        /// </summary>
        internal static string PastingData {
            get {
                return ResourceManager.GetString("PastingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegando fórmulas.
        /// </summary>
        internal static string PastingFormulas {
            get {
                return ResourceManager.GetString("PastingFormulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivotando los datos.
        /// </summary>
        internal static string PivotingData {
            get {
                return ResourceManager.GetString("PivotingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, espere.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando datos.
        /// </summary>
        internal static string ProcessingData {
            get {
                return ResourceManager.GetString("ProcessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrescar hoja.
        /// </summary>
        internal static string RefreshSheet {
            get {
                return ResourceManager.GetString("RefreshSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y enviar.
        /// </summary>
        internal static string SaveAndSend {
            get {
                return ResourceManager.GetString("SaveAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviando correo electrónico.
        /// </summary>
        internal static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar la planilla de carga únicamente.
        /// </summary>
        internal static string ShowLoadTemplateOnly {
            get {
                return ResourceManager.GetString("ShowLoadTemplateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado no envia notifiaciones.
        /// </summary>
        internal static string StateNotSendNotification {
            get {
                return ResourceManager.GetString("StateNotSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado anterior.
        /// </summary>
        internal static string StatusBefore {
            get {
                return ResourceManager.GetString("StatusBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione {0} opciones únicamente.
        /// </summary>
        internal static string TwoOptionsOnly {
            get {
                return ResourceManager.GetString("TwoOptionsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subiendo datos.
        /// </summary>
        internal static string UploadingData {
            get {
                return ResourceManager.GetString("UploadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar datos.
        /// </summary>
        internal static string ViewData {
            get {
                return ResourceManager.GetString("ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su nodo.
        /// </summary>
        internal static string YourNode {
            get {
                return ResourceManager.GetString("YourNode", resourceCulture);
            }
        }
    }
}
