//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PublicResources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PublicResources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea blanquear la contraseña?.
        /// </summary>
        public static string ConfirmPasswordClear {
            get {
                return ResourceManager.GetString("ConfirmPasswordClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso denegado..
        /// </summary>
        public static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al iniciar la aplicación..
        /// </summary>
        public static string ErrorAppInit {
            get {
                return ResourceManager.GetString("ErrorAppInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido conectar al servicio para recuperar la información solicitada..
        /// </summary>
        public static string ErrorConectionService {
            get {
                return ResourceManager.GetString("ErrorConectionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin conexión, asegúrate de tener una conexión activa y estable a Internet..
        /// </summary>
        public static string ErrorConnectionTimeOut {
            get {
                return ResourceManager.GetString("ErrorConnectionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email no encontrado.
        /// </summary>
        public static string ErrorEmailNotFound {
            get {
                return ResourceManager.GetString("ErrorEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ocurrio un error! No se ha enviado un correo de confirmación de cuenta..
        /// </summary>
        public static string ErrorMailConfirmationSend {
            get {
                return ResourceManager.GetString("ErrorMailConfirmationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La página solicitada no se ha encontrado..
        /// </summary>
        public static string ErrorPageNotFound {
            get {
                return ResourceManager.GetString("ErrorPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo blanquear la contraseña..
        /// </summary>
        public static string ErrorPasswordClear {
            get {
                return ResourceManager.GetString("ErrorPasswordClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Clave y Repetir Clave deben coincidir..
        /// </summary>
        public static string ErrorPasswordEqual {
            get {
                return ResourceManager.GetString("ErrorPasswordEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Clave no posee la longitud mínima..
        /// </summary>
        public static string ErrorPasswordMinLength {
            get {
                return ResourceManager.GetString("ErrorPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Repetir Clave no posee la longitud mínima..
        /// </summary>
        public static string ErrorRepeatPasswordMinLenght {
            get {
                return ResourceManager.GetString("ErrorRepeatPasswordMinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud tiene una sintaxis incorrecta..
        /// </summary>
        public static string ErrorRequestSyntaxIncorrect {
            get {
                return ResourceManager.GetString("ErrorRequestSyntaxIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Usuario no posee la longitud mínima..
        /// </summary>
        public static string ErrorUserFieldMinLength {
            get {
                return ResourceManager.GetString("ErrorUserFieldMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar de aplicación.
        /// </summary>
        public static string InfoChangeApp {
            get {
                return ResourceManager.GetString("InfoChangeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación se completo con éxito. Verifique su cuenta de e-mail..
        /// </summary>
        public static string InfoEmailCheck {
            get {
                return ResourceManager.GetString("InfoEmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña blanqueada exitosamente..
        /// </summary>
        public static string InfoPasswordClear {
            get {
                return ResourceManager.GetString("InfoPasswordClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se enviará al teléfono registrado una nueva contraseña temporal..
        /// </summary>
        public static string InfoPasswordPhoneMessage {
            get {
                return ResourceManager.GetString("InfoPasswordPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión ha expirado.
        /// </summary>
        public static string InfoSessionExpired {
            get {
                return ResourceManager.GetString("InfoSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya hay un usuario iniciado sesión en el navegador..
        /// </summary>
        public static string InfoUserLoggedIn {
            get {
                return ResourceManager.GetString("InfoUserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado.
        /// </summary>
        public static string InfoUserUnAuthorized {
            get {
                return ResourceManager.GetString("InfoUserUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Éxito! Se ha enviado un correo de confirmación de cuenta..
        /// </summary>
        public static string SuccessMailConfirmationSend {
            get {
                return ResourceManager.GetString("SuccessMailConfirmationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su clave ha sido modificada con éxito..
        /// </summary>
        public static string SuccessPasswordUpdate {
            get {
                return ResourceManager.GetString("SuccessPasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido creado..
        /// </summary>
        public static string SuccessUserCreate {
            get {
                return ResourceManager.GetString("SuccessUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido actualizado..
        /// </summary>
        public static string SuccessUserUpdate {
            get {
                return ResourceManager.GetString("SuccessUserUpdate", resourceCulture);
            }
        }
    }
}
