//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.Webapp.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.Webapp.Texts.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuntar archivo.
        /// </summary>
        internal static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con.
        /// </summary>
        internal static string AtTimeCron {
            get {
                return ResourceManager.GetString("AtTimeCron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para agregar más de un correo presione COMA o ENTER para agregarlo.
        /// </summary>
        internal static string BFPSendEmailHint {
            get {
                return ResourceManager.GetString("BFPSendEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos que no son Zapatos.
        /// </summary>
        internal static string ConditionExample_1 {
            get {
                return ResourceManager.GetString("ConditionExample_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;Zapatos.
        /// </summary>
        internal static string ConditionExample_1_value {
            get {
                return ResourceManager.GetString("ConditionExample_1_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos que empiezan con A.
        /// </summary>
        internal static string ConditionExample_2 {
            get {
                return ResourceManager.GetString("ConditionExample_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos que son Pantalones.
        /// </summary>
        internal static string ConditionExample_3 {
            get {
                return ResourceManager.GetString("ConditionExample_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantalones.
        /// </summary>
        internal static string ConditionExample_3_value {
            get {
                return ResourceManager.GetString("ConditionExample_3_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diariamente.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día(s).
        /// </summary>
        internal static string Day_s {
            get {
                return ResourceManager.GetString("Day/s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada.
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo de condiciones.
        /// </summary>
        internal static string ExampleOfConditions {
            get {
                return ResourceManager.GetString("ExampleOfConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinto.
        /// </summary>
        internal static string Fifth {
            get {
                return ResourceManager.GetString("Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuarto.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora(s).
        /// </summary>
        internal static string Hour_s {
            get {
                return ResourceManager.GetString("Hour/s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada hora.
        /// </summary>
        internal static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un ejemplo para crear conceptos calculados es: crear una measure DAX que obtenga la suma del Value del Modelo y filtre por el/los concepto(s) que se deseen.
        /// </summary>
        internal static string InfoQueryDaxCalculatedConceptsDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxCalculatedConceptsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ESCALAR) Tiene que devolver un valor único.
        /// </summary>
        internal static string InfoQueryDaxCalculatedConceptsReturnValues {
            get {
                return ResourceManager.GetString("InfoQueryDaxCalculatedConceptsReturnValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalúa una expresión en un contexto modificado por filtros..
        /// </summary>
        internal static string InfoQueryDaxCalculateDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxCalculateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La expresión que se va a evaluar..
        /// </summary>
        internal static string InfoQueryDaxCalculateParamExpression {
            get {
                return ResourceManager.GetString("InfoQueryDaxCalculateParamExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Opcional) (Repetible) Una expresión booleana -Verdadero/Falso- o una expresión de tabla que define un filtro..
        /// </summary>
        internal static string InfoQueryDaxCalculateParamFilter {
            get {
                return ResourceManager.GetString("InfoQueryDaxCalculateParamFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ESCALAR): devuelve un valor único de cualquier tipo..
        /// </summary>
        internal static string InfoQueryDaxCalculateReturnValues {
            get {
                return ResourceManager.GetString("InfoQueryDaxCalculateReturnValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La palabra clave COLUMN permite definir una columna en una consulta (en la sección DEFINE).&amp;lt;br/&amp;gt; La columna no se persistirá en el modelo, solo existe en la duración de la query. &amp;lt;/br&amp;gt; Será como una columna calculada en todos los sentidos.
        /// </summary>
        internal static string InfoQueryDaxDefineColumnDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxDefineColumnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La palabra clave MEASURE introduce una definición de medida en una consulta (en la sección DEFINE).&amp;lt;br/&amp;gt; La sintaxis después de MEASURE define una medida, que se puede utilizar en cualquier otra expresión de la misma consulta.&amp;lt;br/&amp;gt; Sobreescribe la medida modelo con el mismo nombre en la duración de la query. Esto no afectará a la mesaure del modelo.
        /// </summary>
        internal static string InfoQueryDaxDefineMeasuresDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxDefineMeasuresDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La palabra clave TABLE introduce una definición de tabla en una consulta (en la sección DEFINE).&amp;lt;br/&amp;gt; La tabla no es persistida en el modelo, solo existe mientras dure la consulta..
        /// </summary>
        internal static string InfoQueryDaxDefineTableDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxDefineTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La palabra clave VAR introduce variables en una expresión.&amp;lt;br/&amp;gt; La sintaxis después de VAR define una variable, que se puede consumir en las siguientes declaraciones VAR o dentro de la declaración RETURN obligatoria después de la declaración de una o más variables.&amp;lt;br/&amp;gt;&amp;lt;br/&amp;gt; Si se usa VAR en la sección DEFINE de una declaración EVALUATE, se puede usar en cualquier expresión de la declaración y no se puede usar la palabra clave RETURN..
        /// </summary>
        internal static string InfoQueryDaxDefineVarDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxDefineVarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVALUATE es una declaración DAX necesaria para ejecutar una consulta. &amp;lt;br/&amp;gt;&amp;lt;br/&amp;gt;EVALUATE seguido de cualquier expresión de tabla devuelve el resultado de la expresión de tabla. &amp;lt;br/&amp;gt;Además, una o más declaraciones EVALUATE pueden ir precedidas de definiciones especiales como tablas, columnas, medidas y variables locales que tienen el alcance de todo el lote de declaraciones EVALUATE ejecutadas juntas. &amp;lt;br/&amp;gt;&amp;lt;br/&amp;gt; EVALUATE se divide en tres partes: &amp;lt;br/&amp;gt;&amp;lt;b&amp;gt;- DEFINE -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoQueryDaxEvaluateDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxEvaluateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite elegir que columnas tomar dada una tabla. A su vez, te permite ponerle alias a las columnas o agregar nuevas columnas por medio de expresiones DAX.
        /// </summary>
        internal static string InfoQueryDaxSelectColumnsDesc {
            get {
                return ResourceManager.GetString("InfoQueryDaxSelectColumnsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Opcional) (Repetible) La expresión de la nueva columna que se agregará..
        /// </summary>
        internal static string InfoQueryDaxSelectColumnsParamExpression {
            get {
                return ResourceManager.GetString("InfoQueryDaxSelectColumnsParamExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Opcional) El nombre de la nueva columna que se agregará..
        /// </summary>
        internal static string InfoQueryDaxSelectColumnsParamName {
            get {
                return ResourceManager.GetString("InfoQueryDaxSelectColumnsParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tabla de la que se seleccionan las columnas..
        /// </summary>
        internal static string InfoQueryDaxSelectColumnsParamTable {
            get {
                return ResourceManager.GetString("InfoQueryDaxSelectColumnsParamTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (TABLA): devuelve una tabla con el mismo número de filas que la tabla especificada como primer argumento..
        /// </summary>
        internal static string InfoQueryDaxSelectColumnsReturnValues {
            get {
                return ResourceManager.GetString("InfoQueryDaxSelectColumnsReturnValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retorna un número determinado de filas según una expresión especificada..
        /// </summary>
        internal static string InfoQueryDaxTopNDescription {
            get {
                return ResourceManager.GetString("InfoQueryDaxTopNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuto(s).
        /// </summary>
        internal static string Minute_s {
            get {
                return ResourceManager.GetString("Minute/s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada minuto.
        /// </summary>
        internal static string Minutely {
            get {
                return ResourceManager.GetString("Minutely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensualmente.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De cada.
        /// </summary>
        internal static string OfEvery {
            get {
                return ResourceManager.GetString("OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El.
        /// </summary>
        internal static string OnThe {
            get {
                return ResourceManager.GetString("OnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar {0}.
        /// </summary>
        internal static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días de la semana (LUN-VIE).
        /// </summary>
        internal static string WeekDayOptions {
            get {
                return ResourceManager.GetString("WeekDayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semanalmente.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anualmente.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
