//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.Webapp.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.Webapp.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de borrar el registro &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteRegister {
            get {
                return ResourceManager.GetString("ConfirmDeleteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de realizar esta acción?.
        /// </summary>
        internal static string ConfirmPerformAction {
            get {
                return ResourceManager.GetString("ConfirmPerformAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han personalizado columnas. Al modificar los niveles se perderán las personalizaciones. ¿Desea continuar?.
        /// </summary>
        internal static string ConfirmPivotColumnsWillBeRebuilt {
            get {
                return ResourceManager.GetString("ConfirmPivotColumnsWillBeRebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hace un tiempo que no registramos actividad en la página, asi que por cuestiones de seguridad estamos por cerrar tu sesión..
        /// </summary>
        internal static string ConfirmStayConnected {
            get {
                return ResourceManager.GetString("ConfirmStayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta por cambiar la jerarquia, todos los niveles se borrarán, ¿Desea continuar?.
        /// </summary>
        internal static string ConfirmViewChangeHierarchyTime {
            get {
                return ResourceManager.GetString("ConfirmViewChangeHierarchyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta por cambiar el modelo, todos los filtros y columnas se borrarán, ¿Desea continuar?.
        /// </summary>
        internal static string ConfirmViewChangeModel {
            get {
                return ResourceManager.GetString("ConfirmViewChangeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, no hemos podido encontrar la página que estás buscando. Puede que la URL esté mal escrita o que la página ya no exista.
        /// </summary>
        internal static string Error404Message {
            get {
                return ResourceManager.GetString("Error404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS! Algo salió mal aquí.
        /// </summary>
        internal static string Error404Title {
            get {
                return ResourceManager.GetString("Error404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El filtro de la dimensión categoria no fue encontrado.
        /// </summary>
        internal static string ErrorDimCategoryFilterNotFound {
            get {
                return ResourceManager.GetString("ErrorDimCategoryFilterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró una dimensión tipo categoria.
        /// </summary>
        internal static string ErrorDimCategoryNotFound {
            get {
                return ResourceManager.GetString("ErrorDimCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error el correo  no es válido.
        /// </summary>
        internal static string ErrorEmailNotValid {
            get {
                return ResourceManager.GetString("ErrorEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La columna esta asociada con una fila subtotal, no se puede borrar..
        /// </summary>
        internal static string ErrorExcelColumnAssociatedWithRowSubtotalCannotRemove {
            get {
                return ResourceManager.GetString("ErrorExcelColumnAssociatedWithRowSubtotalCannotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al existir un nivel, se requiere agregar las filas.
        /// </summary>
        internal static string ErrorExcelColumnDimensionForPivotRequired {
            get {
                return ResourceManager.GetString("ErrorExcelColumnDimensionForPivotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere agregar la fila con campo ID.
        /// </summary>
        internal static string ErrorExcelColumnDimensionIDRequired {
            get {
                return ResourceManager.GetString("ErrorExcelColumnDimensionIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron los filtros de tipo tiempo necesarios para identificar el contexto de datos.
        /// </summary>
        internal static string ErrorFiltersTypeTimeToIndetifyContextDataNotFound {
            get {
                return ResourceManager.GetString("ErrorFiltersTypeTimeToIndetifyContextDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener datos..
        /// </summary>
        internal static string ErrorGenericData {
            get {
                return ResourceManager.GetString("ErrorGenericData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo ya existe..
        /// </summary>
        internal static string ErrorGenericExist {
            get {
                return ResourceManager.GetString("ErrorGenericExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar. La jerarquia seleccionada por defecto no contiene una columna que se encuentra relacionada a un modelo.
        /// </summary>
        internal static string ErrorHierachyRelatedToModel {
            get {
                return ResourceManager.GetString("ErrorHierachyRelatedToModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite valores &apos;null&apos;.
        /// </summary>
        internal static string ErrorIsNulleable {
            get {
                return ResourceManager.GetString("ErrorIsNulleable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nivel no tiene columnas. Se requiere agregarlas..
        /// </summary>
        internal static string ErrorLevelColumnsRequired {
            get {
                return ResourceManager.GetString("ErrorLevelColumnsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se alcanzó el mas bajo nivel de granularidad.
        /// </summary>
        internal static string ErrorLowGranularityNotReached {
            get {
                return ResourceManager.GetString("ErrorLowGranularityNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo no está relacionado con una dimensión concepto.
        /// </summary>
        internal static string ErrorModelNotRelatedToDimConcept {
            get {
                return ResourceManager.GetString("ErrorModelNotRelatedToDimConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay modelos disponibles.
        /// </summary>
        internal static string ErrorModelsNotAvailable {
            get {
                return ResourceManager.GetString("ErrorModelsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La estructura no puede ser borrada.
        /// </summary>
        internal static string ErrorStructureCantNotDeleted {
            get {
                return ResourceManager.GetString("ErrorStructureCantNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del archivo debe ser igual al nombre de la tabla..
        /// </summary>
        internal static string ErrorTableNameImport {
            get {
                return ResourceManager.GetString("ErrorTableNameImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un elemento para continuar.
        /// </summary>
        internal static string ErrorValueMustSelected {
            get {
                return ResourceManager.GetString("ErrorValueMustSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún elemento seleccionado.
        /// </summary>
        internal static string ErrorValueNotSelected {
            get {
                return ResourceManager.GetString("ErrorValueNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso se ejecutará utilizando el usuario Admin del Tenant.
        /// </summary>
        internal static string InfoAdminExecuteProcess {
            get {
                return ResourceManager.GetString("InfoAdminExecuteProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordernar los valores obtenidos para la creación de las nuevas columnas. De esta manera las columnas creadas tendrán este orden..
        /// </summary>
        internal static string InfoColMadeFromFilterSortTooltip {
            get {
                return ResourceManager.GetString("InfoColMadeFromFilterSortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La letra informada es solo representativa y puede variar de acuerdo a los filtros que elija el usuario..
        /// </summary>
        internal static string InfoColsLettersAndColsMadeFromFilters {
            get {
                return ResourceManager.GetString("InfoColsLettersAndColsMadeFromFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estas columnas no se pudieron asociar con ninguna columna del target.
        /// </summary>
        internal static string InfoDataRuleColumnsCustomNoMatched {
            get {
                return ResourceManager.GetString("InfoDataRuleColumnsCustomNoMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ejecutar la vista previa, deberá guardar la regla de datos. Si prefiere probar su consulta DAX sin guardar, recuerde que puede utilizar el Ejecutor de consultas DAX.
        /// </summary>
        internal static string InfoDataRulePreviewTooltip {
            get {
                return ResourceManager.GetString("InfoDataRulePreviewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro agregado por el Nivel de las columnas.
        /// </summary>
        internal static string InfoFilterAddedBylevel {
            get {
                return ResourceManager.GetString("InfoFilterAddedBylevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la jerarquía ingresada ya existe.
        /// </summary>
        internal static string InfoHiearchyNameExist {
            get {
                return ResourceManager.GetString("InfoHiearchyNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero seleccione una jerarquía.
        /// </summary>
        internal static string InfoHierarchyCreate {
            get {
                return ResourceManager.GetString("InfoHierarchyCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una jerarquía a eliminar..
        /// </summary>
        internal static string InfoHierarchyDelete {
            get {
                return ResourceManager.GetString("InfoHierarchyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si esta activado, las nuevas columnas se crearán mediante una consulta a la tabla y se filtrarán con los filtros de la planilla. En caso contrario las nuevas columnas se crean a partir de los datos devueltos por la consulta de la planilla de carga..
        /// </summary>
        internal static string InfoIncludeRecordsWithoutModelValuesCols {
            get {
                return ResourceManager.GetString("InfoIncludeRecordsWithoutModelValuesCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestra todos los registros independientemente de si tienen valores en el modelo.
        /// 
        ///¡Atención!
        ///Esta opción a nivel de &quot;filas&quot; hace implícitamente un &quot;Cross Join&quot; contra todas las tablas.
        ///Por eso, recomendamos filtrar cada una de las demás tablas.
        /// </summary>
        internal static string InfoIncludeRecordsWithoutModelValuesRows {
            get {
                return ResourceManager.GetString("InfoIncludeRecordsWithoutModelValuesRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite modificar la columna seleccionada porque este nivel ya tiene columnas configuradas.
        /// </summary>
        internal static string InfoLevelColSelectDisabledTooltip {
            get {
                return ResourceManager.GetString("InfoLevelColSelectDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite modificar la columna seleccionada porque la dimensión es del tipo Tiempo y esta columna solo puede ser la de la granularidad del modelo.
        /// </summary>
        internal static string InfoLevelTableTimeColSelectDisabledTooltip {
            get {
                return ResourceManager.GetString("InfoLevelTableTimeColSelectDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargue datos para ver columnas aplanadas..
        /// </summary>
        internal static string InfoParentChildLoadDataFlattened {
            get {
                return ResourceManager.GetString("InfoParentChildLoadDataFlattened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliza Columna: [{0}] y Foreign Key: [{1}].
        /// </summary>
        internal static string InfoRelationship {
            get {
                return ResourceManager.GetString("InfoRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar los datos por esta columna.
        /// </summary>
        internal static string InfoSortData {
            get {
                return ResourceManager.GetString("InfoSortData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no selecciona ningún registro, se seleccionarán todos..
        /// </summary>
        internal static string InfoTableMultipleSelection {
            get {
                return ResourceManager.GetString("InfoTableMultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros.
        /// </summary>
        internal static string InfoValuesNotFound {
            get {
                return ResourceManager.GetString("InfoValuesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un valor distinto a -999 para usar como valor por defecto.
        /// </summary>
        internal static string MustSelectDefaultValue {
            get {
                return ResourceManager.GetString("MustSelectDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz clic para filtrar por este Estado.
        /// </summary>
        internal static string StatusFilterAdd {
            get {
                return ResourceManager.GetString("StatusFilterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz clic para quitar el filtro.
        /// </summary>
        internal static string StatusFilterRemove {
            get {
                return ResourceManager.GetString("StatusFilterRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha copiado la regla de datos exitosamente.
        /// </summary>
        internal static string SuccessDataRuleCopy {
            get {
                return ResourceManager.GetString("SuccessDataRuleCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil de reglas de datos se ha agregado exitosamente.
        /// </summary>
        internal static string SuccessDataRuleProfileAdd {
            get {
                return ResourceManager.GetString("SuccessDataRuleProfileAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha actualiazdo la regla de datos exitosamente.
        /// </summary>
        internal static string SuccessDataRuleUpdate {
            get {
                return ResourceManager.GetString("SuccessDataRuleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerarquía eliminada con éxito..
        /// </summary>
        internal static string SuccessHierarchyDelete {
            get {
                return ResourceManager.GetString("SuccessHierarchyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo actualizado exitosamente.
        /// </summary>
        internal static string SuccessNodeUpdate {
            get {
                return ResourceManager.GetString("SuccessNodeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se actualizó el cronograma exitosamente.
        /// </summary>
        internal static string SuccessScheduleUpdated {
            get {
                return ResourceManager.GetString("SuccessScheduleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura creada con éxito.
        /// </summary>
        internal static string SuccessStructureCreated {
            get {
                return ResourceManager.GetString("SuccessStructureCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla importada con éxito..
        /// </summary>
        internal static string SuccessTableImport {
            get {
                return ResourceManager.GetString("SuccessTableImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla actualizada con éxito..
        /// </summary>
        internal static string SuccessTableUpdate {
            get {
                return ResourceManager.GetString("SuccessTableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido borrado..
        /// </summary>
        internal static string SuccessUserDelete {
            get {
                return ResourceManager.GetString("SuccessUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta ha sido bloqueada con éxito..
        /// </summary>
        internal static string SuccessUserLocked {
            get {
                return ResourceManager.GetString("SuccessUserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta ha sido desbloqueada con éxito..
        /// </summary>
        internal static string SuccessUserUnlocked {
            get {
                return ResourceManager.GetString("SuccessUserUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede agregar un nivel porque existe un nivel con columnas reales. Solo se permite reales en el último nivel.
        /// </summary>
        internal static string WarnCannotAddLevelRealsColsExist {
            get {
                return ResourceManager.GetString("WarnCannotAddLevelRealsColsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es irreversible cambiar su origen a una query personalizada. No podrá deshacer este cambio en este Perfil.
        ///Los nombres de las columnas de la consulta que desarrollará deberán coincidir con los nombres de las columnas del destino..
        /// </summary>
        internal static string WarnDataRuleCustom {
            get {
                return ResourceManager.GetString("WarnDataRuleCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite configurar.
        /// </summary>
        internal static string WarnExcelColumnCannotConfigure {
            get {
                return ResourceManager.GetString("WarnExcelColumnCannotConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los usuarios que están logueados, excepto el administrador, serán deslogueados automáticamente de la aplicación. Solamente el administrador podrá utilizar el aplicativo..
        /// </summary>
        internal static string WarnOnDisableTeanant {
            get {
                return ResourceManager.GetString("WarnOnDisableTeanant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Atención! Se borrará la columna: [{0}] y la Foreign Key: [{1}].
        /// </summary>
        internal static string WarnRelationshipDelete {
            get {
                return ResourceManager.GetString("WarnRelationshipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se creará una columna: [{0}]  y una Foreign Key: [{1}].
        /// </summary>
        internal static string WarnRelationshipInsert {
            get {
                return ResourceManager.GetString("WarnRelationshipInsert", resourceCulture);
            }
        }
    }
}
