//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.General.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.General.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea continuar? Hay cambios que se perderán al salir....
        /// </summary>
        internal static string ConfirmChangesWillLost {
            get {
                return ResourceManager.GetString("ConfirmChangesWillLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licencia a expirado.
        /// </summary>
        internal static string ErrorLicenseExpired {
            get {
                return ResourceManager.GetString("ErrorLicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar la entidad.
        /// </summary>
        internal static string ErrorLoadingEntity {
            get {
                return ResourceManager.GetString("ErrorLoadingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no tiene un registro de tipo &quot;Real&quot;. Esta planilla guarda solo datos &quot;reales&quot;..
        /// </summary>
        internal static string ErrorLoadTableModelRealItemNotFound {
            get {
                return ResourceManager.GetString("ErrorLoadTableModelRealItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Telefono no cumple con la cantidad {0} de &apos;{1}&apos; digitos..
        /// </summary>
        internal static string ErrorPhoneNotValid {
            get {
                return ResourceManager.GetString("ErrorPhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error inesperado.
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiración.
        /// </summary>
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron estados para los Ciclos de Aprobación.
        /// </summary>
        internal static string InfoApprovalCycleStatusNotFound {
            get {
                return ResourceManager.GetString("InfoApprovalCycleStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores entre.
        /// </summary>
        internal static string InfoFilterTypeBetweenTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeBetweenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores que contienen.
        /// </summary>
        internal static string InfoFilterTypeContainsTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeContainsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores distintos a.
        /// </summary>
        internal static string InfoFilterTypeDistinctTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeDistinctTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores que terminan con.
        /// </summary>
        internal static string InfoFilterTypeEndsWithTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeEndsWithTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar el valor igual a.
        /// </summary>
        internal static string InfoFilterTypeEqualTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeEqualTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores mayores a.
        /// </summary>
        internal static string InfoFilterTypeHigherTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeHigherTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar los valores.
        /// </summary>
        internal static string InfoFilterTypeInTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeInTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores BLANK.
        /// </summary>
        internal static string InfoFilterTypeIsBlankTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeIsBlankTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores menores a.
        /// </summary>
        internal static string InfoFilterTypeMinorTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeMinorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores que no sean BLANK.
        /// </summary>
        internal static string InfoFilterTypeNotBlankTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeNotBlankTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar los valores que no sean.
        /// </summary>
        internal static string InfoFilterTypeNotInTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeNotInTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar valores que empiezan con.
        /// </summary>
        internal static string InfoFilterTypeStartsWithTooltip {
            get {
                return ResourceManager.GetString("InfoFilterTypeStartsWithTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cargarán datos solo para la dimensión {0} con código {1}.
        /// </summary>
        internal static string InfoLoadTablesModelReals {
            get {
                return ResourceManager.GetString("InfoLoadTablesModelReals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado con éxito.
        /// </summary>
        internal static string SuccessGenericCreate {
            get {
                return ResourceManager.GetString("SuccessGenericCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado con éxito.
        /// </summary>
        internal static string SuccessGenericDelete {
            get {
                return ResourceManager.GetString("SuccessGenericDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación realizada con éxito.
        /// </summary>
        internal static string SuccessGenericMessage {
            get {
                return ResourceManager.GetString("SuccessGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado con éxito.
        /// </summary>
        internal static string SuccessGenericUpdate {
            get {
                return ResourceManager.GetString("SuccessGenericUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurado con éxito.
        /// </summary>
        internal static string SucessGenericRestore {
            get {
                return ResourceManager.GetString("SucessGenericRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambios sin guardar.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licencia expira el {0}.
        /// </summary>
        internal static string WarnLicenseExpiringSoon {
            get {
                return ResourceManager.GetString("WarnLicenseExpiringSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo tiene asociada una dimensión Tiempo pero no tiene configurada su Granularidad. Favor de configurarlo en el ABM del modelo.
        /// </summary>
        internal static string WarnModelMustHaveTimeGranularity {
            get {
                return ResourceManager.GetString("WarnModelMustHaveTimeGranularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen cambios sin guardar.
        /// </summary>
        internal static string WarnUnsavedChanges {
            get {
                return ResourceManager.GetString("WarnUnsavedChanges", resourceCulture);
            }
        }
    }
}
