//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgFotos.Core.Localization.PrivateResources.WebappRoot.Fields {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgFotos.Core.Localization.PrivateResources.WebappRoot.Fields.Fields", typeof(Fields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicaciones.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle auditoría.
        /// </summary>
        internal static string AuditDetail {
            get {
                return ResourceManager.GetString("AuditDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar endpoints automáticamente .
        /// </summary>
        internal static string AutoRegisterEndpoints {
            get {
                return ResourceManager.GetString("AutoRegisterEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente {0}.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear base de datos.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personaliza el tema.
        /// </summary>
        internal static string CustomizeTheme {
            get {
                return ResourceManager.GetString("CustomizeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la base de datos.
        /// </summary>
        internal static string DataBaseName {
            get {
                return ResourceManager.GetString("DataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se asignará por defecto, al usuario Administrador, cuando se cree un nuevo Tenant.
        /// </summary>
        internal static string DefaultAssignAdminNewTenant {
            get {
                return ResourceManager.GetString("DefaultAssignAdminNewTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir icono indicando el nombre.
        /// </summary>
        internal static string DefineIconName {
            get {
                return ResourceManager.GetString("DefineIconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        internal static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepción.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar menús.
        /// </summary>
        internal static string FilterMenus {
            get {
                return ResourceManager.GetString("FilterMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar permisos.
        /// </summary>
        internal static string FilterPermissions {
            get {
                return ResourceManager.GetString("FilterPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo HTTP.
        /// </summary>
        internal static string HTTPMethod {
            get {
                return ResourceManager.GetString("HTTPMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del icono.
        /// </summary>
        internal static string IconName {
            get {
                return ResourceManager.GetString("IconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url del icono.
        /// </summary>
        internal static string IconUrl {
            get {
                return ResourceManager.GetString("IconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento de licencia.
        /// </summary>
        internal static string LicenseExpiration {
            get {
                return ResourceManager.GetString("LicenseExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de licencia.
        /// </summary>
        internal static string LicenseStart {
            get {
                return ResourceManager.GetString("LicenseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de licencia.
        /// </summary>
        internal static string LicenseType {
            get {
                return ResourceManager.GetString("LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        internal static string Listing {
            get {
                return ResourceManager.GetString("Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de diseño del Login.
        /// </summary>
        internal static string LoginLayoutType {
            get {
                return ResourceManager.GetString("LoginLayoutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de mensajes.
        /// </summary>
        internal static string MessageTemplate {
            get {
                return ResourceManager.GetString("MessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros.
        /// </summary>
        internal static string Paramenters {
            get {
                return ResourceManager.GetString("Paramenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de dato del parámetro.
        /// </summary>
        internal static string ParameterDataType {
            get {
                return ResourceManager.GetString("ParameterDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú Padre.
        /// </summary>
        internal static string ParentMenu {
            get {
                return ResourceManager.GetString("ParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Permiso.
        /// </summary>
        internal static string PermissionCode {
            get {
                return ResourceManager.GetString("PermissionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant..
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerar todos los temas.
        /// </summary>
        internal static string RegenerateAllThemes {
            get {
                return ResourceManager.GetString("RegenerateAllThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer valor.
        /// </summary>
        internal static string RestoreValue {
            get {
                return ResourceManager.GetString("RestoreValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restringido.
        /// </summary>
        internal static string Restricted {
            get {
                return ResourceManager.GetString("Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        internal static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de enrutamiento.
        /// </summary>
        internal static string RoutingPath {
            get {
                return ResourceManager.GetString("RoutingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el permiso padre.
        /// </summary>
        internal static string SelectParentPermission {
            get {
                return ResourceManager.GetString("SelectParentPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar módulos / controladores con items seleccioandos.
        /// </summary>
        internal static string ShowModulesAndControlsWithSelectedItems {
            get {
                return ResourceManager.GetString("ShowModulesAndControlsWithSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenamiento.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbol.
        /// </summary>
        internal static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver base de datos.
        /// </summary>
        internal static string ViewDatabase {
            get {
                return ResourceManager.GetString("ViewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible en accesos directos.
        /// </summary>
        internal static string VisibleInHomeShortcuts {
            get {
                return ResourceManager.GetString("VisibleInHomeShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible en menú.
        /// </summary>
        internal static string VisibleInMenu {
            get {
                return ResourceManager.GetString("VisibleInMenu", resourceCulture);
            }
        }
    }
}
